### ISSUE TITLE
Unable to handle spaces in project path

### ISSUE THREAD

**Issue by Sembazuru** [openscopeproject/InteractiveHtmlBom#1]
The path for the project that I'm trying to use this script for is:
"C:\Users\Chris\Google Drive\Barrel of Makers\Windmill LED panel\Schematic\I&O_Epander"

I get an error that Windows can't find "C:\Users\Chris\Google".

I'm running this in the 2018-07-25 release of 5.0.0 on 64bit Win10.

**Comment by qu1ck** [comment]
But you still get bom generated, right?
It's just the last bit to open html in browser that fails. I'll fix that soon.

**Comment by Sembazuru** [comment]
Oh, I hadn't noticed. I got the error so quickly that I though it was crapping out making the bom folder.

Yes, I did get the generated BOM.
