### ISSUE TITLE
Is it possible to build the bom from just gerbers and position files?

### ISSUE THREAD

**Issue by mkschreder** [openscopeproject/InteractiveHtmlBom#101]
Is it possible to build the interactive view from just gerbers and component position files allowing one to search for components?

**Comment by qu1ck** [comment]
No, gerber files have no information about components, only about pcb layers.

**Comment by mkschreder** [comment]
The placement file has information about components.

**Comment by mkschreder** [comment]
It should be possible to at least reconstruct the placement of references.

**Comment by mkschreder** [comment]
I started looking at it and what I have done so far is export gerbers from
gerbview to kicad pcb format and for now without the placement data. The
interactive bom script says it failed to parse the file. Possibly because
there is no module data in the file. I have no time to look further into it
but I'm thinking I could use kicad-library-utils and parse the placement
data and then create dummy modules in the kicad pcb file and try exporting
again. Would be very helpful because I have old gerbers with placement
files that I want to browse this way.

**Comment by qu1ck** [comment]
If you provide examples of files I can look into it more but I highly doubt placement files have anything other than positions of component centers and some part id (not board component reference) which is not enough. At the minimum bom needs board reference, value and footprint.

> The interactive bom script says it failed to parse the file. 

How are you running it and what is the exact error message?

**Comment by qu1ck** [comment]
I will close this for inactivity unless I hear from you in a few days.
