### ISSUE TITLE
Bounding box of rotated parts

### ISSUE THREAD

**Issue by shufps** [openscopeproject/InteractiveHtmlBom#104]
Wow, I love this plugin sooo much 😍 Great work!

I figured out, it would be nice to also rotate the bounding box of a part if the part itself is rotated.

![image](https://user-images.githubusercontent.com/3079832/61614152-5045c400-ac63-11e9-8a85-44ea5d7fbd90.png)

Also it would be nice if the selection in the part list would be clickable - so it doesn't deselect the selected part if the mouse is moved.

Just my two observations with fresh eyes :)

Keep up the awesome work! 😍

**Comment by qu1ck** [comment]
Bounding boxes are calculated that way in pcbnew, it's not currently done by plugin. I suppose I could calculate them manually and rotate appropriately but that will make click detection quite a bit harder.

Regarding clicking on rows, there is #88 already.

**Comment by shufps** [comment]
wow! thank you thank you thank you <3
