### ISSUE TITLE
Wrong values reported in bom.

### ISSUE THREAD

**Issue by Seryogurt** [openscopeproject/InteractiveHtmlBom#105]
[test.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/3456182/test.zip)
If i create schematic with 4 capacitors included- first 0,001uF and three others 0,1uF, then in BOM all four caps appears as 0,1uF in one position. 
Kicad 5.1.2

**Comment by qu1ck** [comment]
Thanks for the bug report, most likely this is caused by comma decimal delimiter. I'll look into it.

**Comment by qu1ck** [comment]
Let me know if the fix works for you. I try to detect user's locale and use the right decimal separator. It works for me when I tried it with German locale.

You have to have system locale set correctly for this detection to work.
