### ISSUE TITLE
v2.2 release is out of sync?

### ISSUE THREAD

**Issue by diegoherranz** [openscopeproject/InteractiveHtmlBom#107]
The files within `InteractiveHtmlBom.zip` don't seem to match the v2.2 tag.
For instance, the stats feature is not available.
The `Source code (zip)` is OK, though. I guess that is because it is automatically generated by github from the tag?

Thanks!

**Comment by qu1ck** [comment]
Thanks for noticing, looks like I uploaded v2.1 archive by mistake. It's fixed now.

**Comment by diegoherranz** [comment]
Thanks for the quick reply. And thanks for the nice plugin.
