### ISSUE TITLE
Export assembly drawing

### ISSUE THREAD

**Issue by Munken** [openscopeproject/InteractiveHtmlBom#110]
Hi

Is it possible to export the generated assembly figures to png, pdf or svg?
Either from the generated html page or as a commandline option.

Regards

**Comment by qu1ck** [comment]
Are you looking for image with or without highlights of component groups? If with highlights, then separate images for all of them?
Have you looked at plotting in pcbnew, it can produce svg, or pdf of any layer. It's not exactly the same drawing as what this plugin generates but it might fit your needs.

**Comment by Munken** [comment]
I've tried pcbnew.   
However, I'm missing a way to show the PTH without cluttering the drawing with traces.

Comparison:

InteractiveHtmlBom:  
![assembly](https://user-images.githubusercontent.com/773660/64672794-bcc38f00-d46c-11e9-9dde-037cfbe7e7ee.png)

PCBnew:  
![kicad](https://user-images.githubusercontent.com/773660/64674288-ba633400-d470-11e9-87af-04cd68e5d0f7.png)

**Comment by qu1ck** [comment]
I see, so you want copper items but not tracks/zones.

I can offer 2 workarounds:
1. In pcbnew select all, then `rightclick -> select... -> filter selection...` and select only tracks and zones. Delete them. Plot to svg including appropriate layers. After plotting undo the deletion.
2. In InteractiveHtmlBom switch to single layer view (F or B buttons) and make the drawing as large as possible by dragging the delimiter bar. Take a screenshot using OS utilities (Win+Shift+S works on windows 10, I think cmd+shift+4 on macos).

It is not trivial to add download functionality in ibom itself. Currently the board is rendered on 4 separate canvases, I would have to rerender them on one combined canvas and then somehow trigger a download or "save as" action. I will look into this further and see if it's possible on file:/// url.

**Comment by qu1ck** [comment]
This seems to work at least in chrome:
https://stackoverflow.com/a/30393357
I still have to test this in other browsers but it seems technically doable.
Not sure about UI for this...

**Comment by Munken** [comment]
Thanks for the workarounds. I used option 2 for this.   
However, rendering directly as svg or pdf would be nice.

How about right click -> save as? That would be sufficient UI for me.

**Comment by qu1ck** [comment]
Right click on image is already mapped to reset view.

**Comment by Munken** [comment]
How about just adding a button?

**Comment by qu1ck** [comment]
That's doable but I can only generate raster image (png, not svg or pdf).

**Comment by Munken** [comment]
As long as the resolution can be adjusted, then this is fine.

**Comment by qu1ck** [comment]
You can export images up to 16000x16000 now.
