### ISSUE TITLE
localisation issue in units.py

### ISSUE THREAD

**Issue by BennoG** [openscopeproject/InteractiveHtmlBom#114]
In locations where decimal separator is a ',' kicad crashes with the message.
"in wxWidges with the comment setlocale called directly not using wxlocale.
now there is a mismatch between C/C== and Windows locale"

this can be fixed by commenting line 17 in units.py
   `#locale.setlocale(locale.LC_NUMERIC, '')`

Benno

**Comment by qu1ck** [comment]
Can you post a screenshot of the message? Also add kicad version information and windows version.

**Comment by BennoG** [comment]
Error message and kicad version below.

![kicad-message](https://user-images.githubusercontent.com/12594062/66737403-25d36380-ee6c-11e9-8b36-531a970de35f.png)

![kicad-version](https://user-images.githubusercontent.com/12594062/66737412-2d930800-ee6c-11e9-80ba-e278702a6dba.png)

**Comment by BennoG** [comment]
Updated to 5.1.4 it is working now
