### ISSUE TITLE
Bézier curves in EdgeCuts do not appear in the board drawings

### ISSUE THREAD

**Issue by Muny** [openscopeproject/InteractiveHtmlBom#121]
I imported a DXF drawing for my board outline onto EdgeCuts, and when viewing the board drawings in the exported BOM, the Bézier curves in the edge cuts do not appear. See the images below.

![](https://pcbx.us/muny/cgwh.png)

And in KiCAD:
![](https://pcbx.us/muny/cgwi.png)

Here is a sample project that has one of these curves which you can use to reproduce the issue:
https://f.pcbx.us/ge

Thanks! This is a very awesome tool, it has become part of my workflow for working with KiCAD.

**Comment by qu1ck** [comment]
Yes, Bezier curves are only in nightlies and not supported yet by plugin. I'll implement them soon.

**Comment by qu1ck** [comment]
Fixed in 8587d54

**Comment by Muny** [comment]
Just tried and it works. Very nice job! Thanks.

**Comment by qu1ck** [comment]
I noticed on your screenshots that drill holes of the edge connector pads in kicad are offset but not in ibom render. Is that just because board was modified after bom was generated or is that a bug too?

**Comment by Muny** [comment]
Oh, I hadn't noticed that. They are offset in the design, and haven't been changed. The field I used to do this is "Shape Offset".

**Comment by qu1ck** [comment]
Fixed in a143bd9
