### ISSUE TITLE
Wiki Installation path for all platform update

### ISSUE THREAD

**Issue by bvernoux** [openscopeproject/InteractiveHtmlBom#122]
Could you update the Wiki https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Installation
By adding that we can also use current KiCad installation directory /share/kicad/scripting/plugins
It is very useful for portable KiCad App ...

**Comment by qu1ck** [comment]
I purposefully omitted that one because for most installs it will be in read-only program files directory and thus saving settings will not work.
There are instructions to get full list of directories so that should be enough.

**Comment by qu1ck** [comment]
Mentioned this on wiki.
