### ISSUE TITLE
Feature request: JS callouts extentability

### ISSUE THREAD

**Issue by tablatronix** [openscopeproject/InteractiveHtmlBom#125]
Some kind of JS event callout hooks to extend functionality, eg. 

I am playing around with something like this, could also be tied into things like inventory control and picking etc.

https://youtu.be/oZNod_Mhfro

**Comment by qu1ck** [comment]
Can you expand on what you mean by JS callouts? Maybe an example of integration with outside system?

**Comment by tablatronix** [comment]
That yt video is an example, and the desc is pretty large.

Just events for current selected item etc.

I just hacked in an xhr for example to pass data to a host I control in this example...

```JS
function createRowHighlightHandler(rowid, refs) {
...
     URL = "http://192.168.1.246/?ledindex="+rowid.replace("bomrow","");
    let xhr = new XMLHttpRequest();
    xhr.open("GET", URL,true);
    xhr.send();
```

**Comment by qu1ck** [comment]
I see. Well these are hardly JS callouts, more like http callbacks but it's semantics.
I will think about good way to implement it. What events other than highlight do you think would be useful to have callbacks for?

**Comment by tablatronix** [comment]
sorry , I meant callouts in JS, not actual 'JS callouts' is that a thing?

functionally to callout to a users control function or trigger an event for customization or action.

**Comment by qu1ck** [comment]
I'm not an expert but probably in pure JS apps it's a thing, not in web since browsers sandbox everything.

**Comment by tablatronix** [comment]
ok well to be clear the xhr call has nothing to do with this.

Might be able to just get away with event listeners, but it depends on the scope of how to allow including user code assets. And what data we need to pass to the function etc

**Comment by qu1ck** [comment]
I agree, it's better to make it generic and not limited to http requests. 
I think I'll add ability to inject user js code at bom generation time and that code will be able to add listeners to some events like highlight change, checkbox state change, etc. Then you can do whatever you want in your code.

**Comment by tablatronix** [comment]
Have you thought about this anymore?

**Comment by qu1ck** [comment]
Yes, I have a plan to implement the injectable user js code with listeners as described above and also injectable css and html headers/footers. Just have to find time to implement it.

**Comment by qu1ck** [comment]
This is now supported. In `InteractiveHtmlBom/web/user-file-examples` there are some examples you can copy over into `InteractiveHtmlBom/web` to check how they work and edit as you like.

I will add more info to the wiki soon.
