### ISSUE TITLE
Importing a DXF on silkscreen layer causes ibom file to not render correctly

### ISSUE THREAD

**Issue by neubauek** [openscopeproject/InteractiveHtmlBom#129]
Parts list does not populate. JavaScript error thrown on rendering bottom layer because DXF was imported on bottom layer silkscreen. See attached output file.

[ibom.html.txt](https://github.com/openscopeproject/InteractiveHtmlBom/files/3998803/ibom.html.txt)

**Comment by qu1ck** [comment]
Thanks for bug report.
