### ISSUE TITLE
Crash with latest Kicad

### ISSUE THREAD

**Issue by diggit** [openscopeproject/InteractiveHtmlBom#130]
Hi,
awesome plugin! I can't image PCB assembly without it.

Unfortunately, ibom stopped working with latest Kicad.
Here is screenshot of error when tried to generate ibom.

![2020-01-05_12-11_bom](https://user-images.githubusercontent.com/512025/71779086-f2a8f800-2fb4-11ea-8b7b-aa78dfe0a8d9.png)

(sorry for screenshot, but I don't know where to get it as text)

**Comment by qu1ck** [comment]
Already fixed in e5ea69c3
Update to v2.3.

**Comment by diggit** [comment]
Thanks, I pulled ibom from master to see if it isn't already fixed, but error disappeared after clicking on "refresh plugins" in PCBnew, weird.
