### ISSUE TITLE
AttributeError: 'SHAPE_LINE_CHAIN' object has no attribute 'Point'

### ISSUE THREAD

**Issue by Miceuz** [openscopeproject/InteractiveHtmlBom#131]
I am using a nightly kicad build:

Application: KiCad
Version: 5.99.0-unknown-fd0d5fd~86~ubuntu18.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Platform: Linux 4.15.0-74-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    Build date: Jan  8 2020 15:48:36
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.22
    Boost: 1.65.1
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.58.0
    Compiler: GCC 7.4.0 with C++ ABI 1011

Build settings:
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

![Screenshot from 2020-01-13 15-42-52](https://user-images.githubusercontent.com/533263/72260452-96308300-361b-11ea-9d7c-e7199d70873e.png)

The PCB file on which the fault happens can be downloaded here:

https://github.com/RainDrop-lora/raindrop/blob/master/Electronics/lora-rs485-bridge/lora-bridge.kicad_pcb

**Comment by qu1ck** [comment]
Update your plugin, this is fixed already.
