### ISSUE TITLE
Enable smart sort for resistors and capacitors by default

### ISSUE THREAD

**Issue by mondalaci** [openscopeproject/InteractiveHtmlBom#134]
I'm quite convinced that using smart sort for resistors and capacitors by default (without explicitly clicking on the Value table header) would be the most intuitive behavior.

**Comment by qu1ck** [comment]
I will not make sort by value the default because it's subjective. I find sort by quantity within groups more useful.
There are plans however to make default sort order configurable (#124) so you will be able to achieve this result once that is implemented.
