### ISSUE TITLE
Feature request: Reset chache.

### ISSUE THREAD

**Issue by jneiva08** [openscopeproject/InteractiveHtmlBom#137]
Hi,

I like to know if is possible to add one button to reset the checkbox to clear the cache?
It happens when you finish one board all the checkbox have been placed.
If happens to need to solder again need to clear the cache of web browser. if not do, all checkbox are filled.

Best regards

**Comment by qu1ck** [comment]
It's already supported, double click the checkbox column header to set/reset all.

**Comment by Crazor** [comment]
This should be mentioned in the "Usage" wiki page, under "BOM page mouse actions". I would have added that myself, but unfortunately, the wiki seems to be read-only for me.

**Comment by qu1ck** [comment]
Good point, updated the wiki.
