### ISSUE TITLE
[wish] Save, save as and load the current board.

### ISSUE THREAD

**Issue by viejolobo** [openscopeproject/InteractiveHtmlBom#138]
I would like to use the tool in small series production. To do this, I have to be able to save the current status of the circuit board and load it again later.

I want to specify a path where I want to save the file.

**Comment by qu1ck** [comment]
![image](https://user-images.githubusercontent.com/3622532/77145206-17096200-6a45-11ea-88f6-60d06c6d6b01.png)

How do existing options not work for you?

**Comment by viejolobo** [comment]
No, I mean while working with the ibom...
![ibom01](https://user-images.githubusercontent.com/62418934/77398392-b90fae00-6da7-11ea-9544-6a7db004e914.png)

**Comment by qu1ck** [comment]
So you want export button to open a "Save as" dialog instead of just putting it in browser downloads?
Not sure what exactly you meant by state in the first message. Checkboxes?

**Comment by viejolobo** [comment]
I want to use iBom in the production of small series. For this I want to write a file with a serial number after assembling the first PCB. Then populate the second PCB etc. At the end I have n files where all components are populated and all check boxes are checked.
Saving as in the browser only saves the bare HTML ...

**Comment by qu1ck** [comment]
Right, so you want to store the state of checkboxes, that's what the export button is for. I'll look into how to make a save as dialog appear.

Or do you want a button that will save html + checkbox state in that html?

**Comment by qu1ck** [comment]
Closing as not feasible. Both saving html and download "save as" dialog is controlled by browser.
