### ISSUE TITLE
same value but different columns

### ISSUE THREAD

**Issue by scarrrr316** [openscopeproject/InteractiveHtmlBom#141]
![image](https://user-images.githubusercontent.com/43269183/79009120-6567d780-7b91-11ea-8727-ac4a49252cd8.png)
same as title ，value are same ，but in different columns，why , BUG? THX

**Comment by qu1ck** [comment]
50v vs 50V
Not quite the same value.

**Comment by scarrrr316** [comment]
What The.......ok......
