### ISSUE TITLE
Suggested changes to the Installation Instructions on the Wiki

### ISSUE THREAD

**Issue by drojf** [openscopeproject/InteractiveHtmlBom#147]
I wanted to suggest some fixes/changes to the "Installation" page. Unfortunately, GitHub doesn't let me make a pull request to the wiki page, so I will provide a link to the raw markdown in this issue, and link to a fork of the repository where you can preview the changes.

I wanted to change the following three things:
- The windows install path on the install page was stated as `%APPDATA%\roaming\kicad\scripting\plugins`, which didn't work on my system. `%APPDATA%` confusingly expands to `C:\Users\[USERNAME]\AppData\Roaming` - that is, the `roaming` part is already included. So to fix this, I just removed the `roaming` part from the path, resulting in `%APPDATA%\kicad\scripting\plugins`
- Move the "You may need to create these folders if they don't exist" part to before the list of install paths, and highlight it in bold.
- General reformatting of the page by adding headings and numbered bullet points

The updated page can be viewed here: https://github.com/drojf/InteractiveHtmlBom/wiki/Installation . I have not changed any other page besides the installation page.

I've uploaded the raw markdown for the page here: https://gist.githubusercontent.com/drojf/b75174f8c62e8896166f4d154b7f353a/raw/bce2ae5f1ff507600cde3955f2f20d5691c919b0/Installation.md

**Comment by qu1ck** [comment]
Thanks, updated.
