### ISSUE TITLE
Plugin crashes on default run

### ISSUE THREAD

**Issue by GioCC** [openscopeproject/InteractiveHtmlBom#149]
I tried to install the plugin and launch the script on a sample PCB with default (untouched) parameters, but I got the trace below:

![Screen Shot 05-01-20 at 03 59 PM](https://user-images.githubusercontent.com/25667790/80810868-0829d980-8bc5-11ea-88c4-c69e3b9b04ad.PNG)

PCB file is also attached.
[I2CKeypad.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/4564574/I2CKeypad.zip)

Kicad version was a recent nightly:

Application: Pcbnew
Version: (5.99.0-1452-gb67f18b39), release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.66.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.1.1) nghttp2/1.39.2
Platform: Windows 8 (build 9200), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    Build date: Apr 28 2020 21:01:01
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8)
    Boost: 1.71.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.66.0
    Compiler: GCC 9.2.0 with C++ ABI 1013

Build settings:
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=OFF
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

**Comment by qu1ck** [comment]
This is fixed in master, please update to latest version.
