### ISSUE TITLE
~Inverted~ names on silkscreen not supported

### ISSUE THREAD

**Issue by ColinBathe** [openscopeproject/InteractiveHtmlBom#154]
If you have text on the silkscreen layer that uses ~ to add a bar on the top, then this isn't supported on BOM html output display.

i.e.
If you have text on the silkscreen layer which contains ~Reset~ then this will appear within Kicad as Reset with a bar over the top. However, within the BOM html output, it appears as ~Reset~

Yeah, ok, this isn't a high priority to fix.

**Comment by ColinBathe** [comment]
![image](https://user-images.githubusercontent.com/24269597/81540585-c4c02f80-9369-11ea-8a87-a0f603db0879.png)
![image](https://user-images.githubusercontent.com/24269597/81540643-da355980-9369-11ea-8cea-9d214397e59a.png)

**Comment by qu1ck** [comment]
I have a fix ready but it's pending resolution on https://gitlab.com/kicad/code/kicad/-/issues/4396
Text rendering logic in kicad may change slightly and I'll follow suit.
