### ISSUE TITLE
Double-click on checkbox columns headers doesn't work when "darken when checked" option is enabled

### ISSUE THREAD

**Issue by ChernyshevDS** [openscopeproject/InteractiveHtmlBom#156]
When double-clicked on header, table column with checkboxes (either Sourced or Placed) is supposed to check or uncheck all contained checkboxes. Unfortunately, it doesn't work when this column is selected in `darken when checked` option menu. I tracked this error to `checkboxSetUnsetAllHandler` - it calls `checkbox.onchange()` handler directly, without creating event args object, which in turn causes `createCheckboxChangeHandler` to fail when trying to use event arguments to find parent elements. Sorry, but my JavaScript-fu is not strong enough to fix it myself :(.
As a temporary workaround, the user may set `darken when checked` option to `None` before clicking on column headers.

**Comment by qu1ck** [comment]
Thanks for the report and digging into the cause.

**Comment by ChernyshevDS** [comment]
Thanks for the olympic fix speed :)
