### ISSUE TITLE
Broken --variants-blacklist and --variants-whitelist options

### ISSUE THREAD

**Issue by set-soft** [openscopeproject/InteractiveHtmlBom#162]
Passing any of them raises `TypeError`.
The problem is that these options are specified as taking 1 or more arguments:

```
parser.add_argument('--variants-whitelist', default='', nargs='+',
   help='List of board variants to include in the BOM.')
parser.add_argument('--variants-blacklist', default='', nargs='+',
   help='List of board variants to exclude from the BOM.')
```

It means that `args.variants_whitelist` and `args.variants_blacklist` are vectors.
But then they are parsed as strings:

```
self.board_variant_whitelist = self._split(args.variants_whitelist)
self.board_variant_blacklist = self._split(args.variants_blacklist)
```

With `_split` expecting a **string**:

```    
@staticmethod
def _split(s):
    """Splits string by ',' and drops empty strings from resulting array."""
    return [a.replace('\\,', ',') for a in re.split(r'(?<!\\),', s) if a]
```

This problem has two possible solutions:
1. Change the command line specification and look for just one argument, and then split it using `_split`. This is coherent with other options like --sort-order, --blacklist and --extra-fields.
2. Mantain the current command line specification and don't use `_split`

I vote for the first option.
I'm not doing a pull-request because I don't know which option is preferred.

**Comment by qu1ck** [comment]
Thanks, I agree first option is better.
