### ISSUE TITLE
mark placed parts also on assembly view

### ISSUE THREAD

**Issue by nopeppermint** [openscopeproject/InteractiveHtmlBom#176]
If I manually check the placed parts I always mark the placed parts on my bom AND also on my assembly view with a light pen.

In InteractiveHtmlBom the marking inside the bom is implemented done with the cross in the checkbox but the assembly view is always the same, independent of the checkbox state.

For me that's a missing feature.

@qu1ck if you could give me a hint where to start I might try to implement this on my own

current:
C1 is selected and C2 is already placed
![part2](https://user-images.githubusercontent.com/3403218/91357671-eac2f000-e7f1-11ea-9dc2-7191c0246cd6.png)

new (mockup):
C1 is selected and C2 is already placed (marked with green overlay on assembly view)
![new](https://user-images.githubusercontent.com/3403218/91357689-f0203a80-e7f1-11ea-82c5-7738e633da51.png)

I am not sure if a green overlay is the best color, maybe someone else has a better idea?

**Comment by qu1ck** [comment]
I like this idea but I think UI needs to be considered, this should be an option and probably somehow combined with "Darken when checked" as they are very similar.

If you want to look how it may be done take a look at getStoredCheckboxRefs() in ibom.js which will return list of component indexes that are currently marked for the given checkbox and drawHighlights()/drawModules() in render.js for how highlighting is done. You could just do second pass over all modules and only draw ones with index that is included in corresponding checkbox refset and draw them with transparent green.

**Comment by nopeppermint** [comment]
> UI needs to be considered, this should be an option and probably somehow combined with "Darken when checked" as they are very similar.

I agree

And thanks for the hints where to start
