### ISSUE TITLE
Saving the HTML with the checkboxes checked

### ISSUE THREAD

**Issue by JackTheEngineer** [openscopeproject/InteractiveHtmlBom#179]
Hello !

Thank you for creating this awesome plugin ! It is really great. 
Is it possible to save the checkbox state within the HTML file ? 
It would be really great to have this portable format to exchange information about what parts are missing / sourced.

Best regards

**Comment by JackTheEngineer** [comment]
In case that it's possible, would it be possible to add an optional comment field, that gets saved too ?

**Comment by qu1ck** [comment]
No, it's not possible to save state or comments in html as the whole bom table is generated dynamically every time you load the page. But you can share checkbox state by doing config export/import.

![image](https://user-images.githubusercontent.com/3622532/92185397-b8744c80-ee08-11ea-927f-92556fca6a4e.png)

**Comment by qu1ck** [comment]
An easy way to share comments would be to export bom table to a spreadsheet like google sheets or excel and have your comments there.
![image](https://user-images.githubusercontent.com/3622532/92185580-2caef000-ee09-11ea-9032-de4a3e3145bf.png)
Copy button next to the filter field will put the bom table in cipboard from where you can just ctrl-v it into spreadsheet.
