### ISSUE TITLE
Take into account vertical justification of text

### ISSUE THREAD

**Issue by kasbah** [openscopeproject/InteractiveHtmlBom#183]
We are trying to include Eagle imports over on Kitspace in https://github.com/kitspace/kitspace/pull/300 and noticed a slight issue with some of the silkscreen text placement in IBOM. 

Here I have replicated it in IBOM on the master branch:

![image](https://user-images.githubusercontent.com/206854/92949219-9f941880-f452-11ea-9ba6-3b83d708d437.png)

The culprit seems to vertical justification of text. There is an open KiCad issue to [support this in KiCad GUI as well](https://gitlab.com/kicad/code/kicad/-/issues/2375).

Here is an example bit of text. (two full examples: [kicad_pcbs.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/5210344/kicad_pcbs.zip))

```lisp
  (gr_text "1 - +5V\n2 - GADJ_R0\n3 - GADJ_R1\n4 - GADJ_R2\n5 - GADJ_R3\n6 - PT100_OUT\n7 - GND\n8 - VCOMP_PWM\n9 - VFOL_PWM\n10 - VFOL_SENSE\n11 - VCOMP_SENSE\n12 - Z_TRIG" (at 112.3061 125.9586) (layer F.SilkS) (tstamp 55E682B0)
    (effects (font (size 0.77216 0.77216) (thickness 0.089408)) (justify left bottom))
```

The `bottom` seems to not be taken into account by IBOM yet. I believe the value can be one of `top`, `center` or `bottom`.

**Comment by qu1ck** [comment]
@kasbah Should be fixed now, please rebase your fork (or pull if that's how you roll). On that note, submit a PR for your fork, many changes can be incorporated in main repo directly, it will make your life easier later.
