### ISSUE TITLE
AttributeError when clicking "Generate BOM" button

### ISSUE THREAD

**Issue by PaulPillau** [openscopeproject/InteractiveHtmlBom#185]
When I click "Generate BOM" in the GUI, Python throws this exception:

![error](https://user-images.githubusercontent.com/18541281/93390726-73233680-f86e-11ea-8405-41a2e4ad8266.PNG)

This stack trace comes from an almost empty test project that only contains one connector and edge cuts.
I first tried it with my current project but got the same error.

Note that I'm using a portable version of KiCAD 5.1.6 which is available here:
[https://github.com/2wayne/KiCadPortable](url)
I installed the plugin in "C:\KiCadPortable\App\KiCad\share\kicad\scripting\plugins\"

**Comment by qu1ck** [comment]
That's an issue with the installation. To verify it you can try running this in scripting console:

```python
import pcbnew
b = pcbnew.GetBoard()
m = list(b.GetModules())[0]
mcopy = pcbnew.MODULE(m)
```
The last line should fail judging by the stack trace from the screenshot. This indicates that pcbnew API is broken, likely not all files were properly updated in the portable kicad install.

**Comment by PaulPillau** [comment]
That last line is indeed the problem.
I installed 5.1.6 normally and it works perfectly now.

Thanks for the quick reply!
