### ISSUE TITLE
Still seeing some silkscreen issues on Eagle imports

### ISSUE THREAD

**Issue by kasbah** [openscopeproject/InteractiveHtmlBom#193]
Hey, following on from #183. We are still seeing some issues with silkscreen items, graphical ones, that look fine in KiCad but are scaled or transposed in IBOM. This is with the same [kicad_pcb files](https://github.com/openscopeproject/InteractiveHtmlBom/files/5210344/kicad_pcbs.zip). I am not sure what the culprit is yet but you can see it e.g. on the flame: 

![image](https://user-images.githubusercontent.com/206854/95497156-ce41d800-0999-11eb-9903-22c886a3161d.png)

http://eagle-ibom.preview.kitspace.org/interactive_bom/?github.com/pyr0ball/pyr0piezo/Pyr0-Piezo%20Z-Probe%20Business%20Card%20DIY%20Module

In KiCad:

![image](https://user-images.githubusercontent.com/206854/95497333-12cd7380-099a-11eb-980d-f5baff56b49b.png)

```kicad_pcb
  (module Pyr0-Piezo-v2-DIY-Business-Card:LOGO-PYR0BALL-KEEPOUT-20MM (layer Top) (tedit 0) (tstamp 5F4FABC3)
    (at 168.1861 87.8586)
    (fp_text reference U$1 (at 0 0) (layer F.SilkS) hide
      (effects (font (size 1.27 1.27) (thickness 0.15)))
    )
    (fp_text value "" (at 0 0) (layer F.SilkS) hide
      (effects (font (size 1.27 1.27) (thickness 0.15)))
    )
    (fp_poly (pts (xy -6.773831 0.172465) (xy -6.774159 0.133303) (xy -6.774159 0.094075) (xy -6.774159 0.026962)
    ...
   ))

```

or the text here:

![image](https://user-images.githubusercontent.com/206854/95497195-d8fc6d00-0999-11eb-9f4b-360e7b4416b0.png)

http://eagle-ibom.preview.kitspace.org/interactive_bom/?github.com/joeycastillo/The-Open-Book/eBook-Wing

In KiCad:

![image](https://user-images.githubusercontent.com/206854/95497512-5b852c80-099a-11eb-80e7-d4e85a7813ac.png)

```kicad_pcb
  (module OSO-BOWI-A1-05:OSO_WORDMARK_125X1300MIL_1000DPI (layer Top) (tedit 0) (tstamp 5F50014C)
    (at 153.8351 146.4056)
    (fp_text reference U$11 (at 0 0) (layer F.SilkS) hide
      (effects (font (size 1.27 1.27) (thickness 0.15)))
    )
    (fp_text value "" (at 0 0) (layer F.SilkS) hide
      (effects (font (size 1.27 1.27) (thickness 0.15)))
    )
    (fp_poly (pts (xy 8.1153 -1.5621) (xy 8.1407 -1.5621) (xy 8.1407 -1.5875) (xy 8.1153 -1.5875)) (layer F.SilkS) (width 0))
    (fp_poly (pts (xy 7.3025 -1.5621) (xy 7.6073 -1.5621) (xy 7.6073 -1.5875) (xy 7.3025 -1.5875)) (layer F.SilkS) (width 0))
    ...
    )
```

**Comment by qu1ck** [comment]
I can't reproduce, when I open the files locally they generate correct boms:

![image](https://user-images.githubusercontent.com/3622532/95508653-32e43f00-0968-11eb-857e-fa3fbb985753.png)
![image](https://user-images.githubusercontent.com/3622532/95508681-3b3c7a00-0968-11eb-9894-f1e50b83d5ee.png)

I remember there was a bug in pcbnew that caused python API to return incorrect offset values after eagle import. But if you closed and reopened the board, then it would be fine. I fixed some of those issues but probably not all.

I'm not sure how your script handles eagle imports but try doing the import, save the file somewhere temporarily and reopen it.

**Comment by kasbah** [comment]
Thanks @quick. I was thinking I should try and reproduce in mainline IBOM first but was too lazy. Serves me right :D
