### ISSUE TITLE
Error with current KiCad nightly

### ISSUE THREAD

**Issue by zonque** [openscopeproject/InteractiveHtmlBom#197]
When running with the latest KiCad nightly, the generation of files fails like this:

![image](https://user-images.githubusercontent.com/106304/99632568-bef48680-2a3d-11eb-9f57-39a535f7a305.png)
(sorry for the image post, I can't copy the text from that dialog)

**Comment by qu1ck** [comment]
Already fixed in 43e5034, please update your plugin.

**Comment by zonque** [comment]
Oops, sorry. I did that of course, but neither "Refresh plugins" nor restarting pcbnew sufficed to pick up the change. I had to restart the project manager as well to make it effective.

**Comment by qu1ck** [comment]
See point 2 here:
https://github.com/openscopeproject/InteractiveHtmlBom/wiki/FAQ#q-i-updated-plugin-to-a-recent-version-and-nothing-changed-or-plugin-behaves-incorrectly

**Comment by zonque** [comment]
:bow:
