### ISSUE TITLE
Running iBOM + Netlist with KiCAD nightly has errors

### ISSUE THREAD

**Issue by whatnick** [openscopeproject/InteractiveHtmlBom#199]
Living on the bleeding edge. Seem to have some issues running iBOM master against KiCAD nightly.

![image](https://user-images.githubusercontent.com/491396/99893002-6b996700-2ccf-11eb-9fbe-9b476634ef77.png)

KiCAD project this was run on is here : https://github.com/whatnick/MCP39F511_Breakout

**Comment by qu1ck** [comment]
Thanks for the fix.
