### ISSUE TITLE
bom list on startup not displayed, even with empty filter

### ISSUE THREAD

**Issue by nopeppermint** [openscopeproject/InteractiveHtmlBom#205]
I just tested current master #7d78c11 and there under Win10 x64 with Firefox 83.0 64bit (and also with Chrome v. 86.0.4240.198 x64) the bom list ist empty on start, even when there is no filter applied.

If you write something and clean it then I expect the same result, but then the bom list is visible:

on startup:

![grafik](https://user-images.githubusercontent.com/3403218/100580626-93e41f80-32e6-11eb-88a7-57153600875c.png)

after writing a filter and cleaning the filter:
![grafik](https://user-images.githubusercontent.com/3403218/100580656-a2cad200-32e6-11eb-9645-e8942b1cc3ba.png)

This is a new issue, before (sry. don't know the version before) it was working.

I used Kicad Application: Pcbnew Version: (5.99.0-7258-g0c2cd1abb2), release build

**Comment by qu1ck** [comment]
Can't reproduce this either. See my comment in #204 for potential solutions.

**Comment by nopeppermint** [comment]
indeed, fixed with https://github.com/openscopeproject/InteractiveHtmlBom/commit/0ecd3b7ef13ebe1b2cdb833930a4b48f8a3def59 thanks
