### ISSUE TITLE
Request  to be able to add partlinks

### ISSUE THREAD

**Issue by bendelathouwer** [openscopeproject/InteractiveHtmlBom#211]
Is it possible to have a field in the html page so we can add the links to the part's mouser/farnell/ etc page

With best regards Ben

**Comment by dreamcat4** [comment]
how about octopart? Does octopart have an http api we can use for that?

**Comment by qu1ck** [comment]
You can use extra fields to put any data you want into the bom, including links. They will be displayed as simple text though, if you want clickable links you will have to write some custom js (see customization in wiki).

**Comment by bendelathouwer** [comment]
> how about octopart? Does octopart have an http api we can use for that?

I'd like a digikey/mouser etc link easyer wen ordering tbh but octopart is a start

**Comment by bendelathouwer** [comment]
> You can use extra fields to put any data you want into the bom, including links. They will be displayed as simple text though, if you want clickable links you will have to write some custom js (see customization in wiki).

So there is no easy way of adding part links to the bom? so I have to edit the htm page?

**Comment by qu1ck** [comment]
You don't have to edit html page to add links. Just add custom fields to parts in eeschema.
