### ISSUE TITLE
Handle symbolic linked script

### ISSUE THREAD

**Issue by clayton13** [openscopeproject/InteractiveHtmlBom#212]
Through trying to set up my system so that one can run simply run `python3 generate_interactive_bom.py ...` I tried to symbolically link from `~/.kicad/scripting/plugins` to `~/.local/bin/` and get the below error. (I think is somewhat relevant to https://github.com/INTI-CMNB/InteractiveHtmlBom/issues/3)

The script returns:
```
  File "/home/clayt/.local/bin/generate_interactive_bom.py", line 23, in <module>
    import InteractiveHtmlBom
ModuleNotFoundError: No module named 'InteractiveHtmlBom'
```
A little logic added here to account for a potential link would solve the issue.
https://github.com/openscopeproject/InteractiveHtmlBom/blob/202f1d34cd3fe47c59cdf4d227af0eb7c0f5083e/InteractiveHtmlBom/generate_interactive_bom.py#L20

 [os.readlink](https://docs.python.org/3/library/os.html#os.readlink) appears to work perfectly as follows:
`script_dir = os.path.dirname(os.path.abspath(os.readlink(__file__)))`

I can make a PR and update the wiki if you agree.

**Comment by qu1ck** [comment]
Use `os.path.realpath` instead, otherwise I agree.
