### ISSUE TITLE
AttributeError: 'BOARD' object has no attribute 'GetModules'

### ISSUE THREAD

**Issue by dwery** [openscopeproject/InteractiveHtmlBom#214]
This is kicad nightly, full version below. I understand the plugin might not be supposed to work, yet, but just wanted to give an heads up.

Version: 5.99.0-unknown-17cf2466aa~106~ubuntu20.10.1, release build

Libraries:
	wxWidgets 3.0.5
	libcurl/7.68.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.8.0 nghttp2/1.40.0 librtmp/2.3

Platform: Linux 5.9.0-1-amd64 x86_64, 64 bit, Little endian, wxGTK, gnome, wayland

Build Info:
	Date: Dec 28 2020 10:18:50
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.71.0
	OCC: 7.4.0
	Curl: 7.68.0
	ngspice: 32
	Compiler: GCC 10.2.0 with C++ ABI 1014

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=ON
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
	KICAD_SCRIPTING_ACTION_MENU=ON
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by qu1ck** [comment]
This is already fixed, get latest version of the plugin from master branch.
