### ISSUE TITLE
Compatibility with KiCad 5.99/6

### ISSUE THREAD

**Issue by rusefillc** [openscopeproject/InteractiveHtmlBom#218]
KiCad 6 is a couple months away, does InteractiveHtmlBom support 5.99 / 6?

We are addicted to InteractiveHtmlBom so KiCad 6 compatibility would drive our migration to version 6.

**Comment by qu1ck** [comment]
Yes, nightly is supported but you have to use latest from master branch and not release package.
This is addressed in [install instructions](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Installation#how-to-install).

**Comment by set-soft** [comment]
> KiCad 6 is a couple months away, does InteractiveHtmlBom support 5.99 / 6?

Just a comment: *a couple* may be 6 months. Some milestone features aren't even implemented.
