### ISSUE TITLE
Error Generating the HTML in nightly

### ISSUE THREAD

**Issue by cebrax** [openscopeproject/InteractiveHtmlBom#219]
I am using KiCad version: (5.99.0-7926-g487aa37d2e)

Here is the error traceback I get when I try to generate the HTML file with default settings:

[https://i.ibb.co/fxxs6T9/error.png](https://i.ibb.co/fxxs6T9/error.png)

**Comment by qu1ck** [comment]
Your nightly is old, update to latest.

**Comment by cebrax** [comment]
Ooops, sorry, seems like KiCad started creating a new directory with the install and my shortcut pointed to the old nightly, sorry
