### ISSUE TITLE
Add "Batch size" setting

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [openscopeproject/InteractiveHtmlBom#227]
1. HTML preferences (menu under "Gear icon") could have this additional setting:
 1.1. Integer field "Batch size" -> Set number of how many boards to be assembled; Default is 1.

2. Values of "Quantity" column should be multiplied by this setting.

This would be useful when counting / moving /preparing components physically to solder a batch of pcbs.

Maybe separate column "Overall quantity" could be also added..

**Comment by qu1ck** [comment]
I feel this kind of number manipulation is much better suited to do outside of ibom. There is a copy bom button for that reason - copy-paste the table to spreadsheet and add/multiply/subtract however you want.
