### ISSUE TITLE
[solved] generated bom html is empty

### ISSUE THREAD

**Issue by rpolasek** [openscopeproject/InteractiveHtmlBom#228]
when i generate a bom and open it in the chromium the bom is emtpy. i'm using last version from github and python v3.9.1. i'm enclosing the generated bom html (zip) and also a screen-shot of my browser with developer tools (jpg) opened.

[dramduino.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/6045460/dramduino.zip)

![screenshot](https://user-images.githubusercontent.com/1434826/109210000-8981d680-77ac-11eb-880f-801d72f881f3.jpg)

**Comment by qu1ck** [comment]
Most likely you didn't restart kicad after updating plugin or didn't remove previous ibom files before updating.

**Comment by rpolasek** [comment]
@qu1ck you're right that was the problem. thank you.
