### ISSUE TITLE
Support curved tracks

### ISSUE THREAD

**Issue by Funkenjaeger** [openscopeproject/InteractiveHtmlBom#229]
KiCad may not support curved tracks, but other EDA tools do (e.g. Eagle/Fusion 360 Electronics via GenericJSON).  
Recommend adding optional fields to the 'tracks' object in the pcbdata struct to support rendering curved traces.

**Comment by qu1ck** [comment]
Kicad also supports them in nightly. I'll add this soon.

**Comment by Funkenjaeger** [comment]
I've got this working on my fork with Eagle/Fusion.  I assumed the same structure as the 'arc' drawing object (start, radius, startangle, endangle).  The changes to render.js to make that work turned out to be trivial (which was good, since I'm not versed in javascript)

Do you know enough about the Kicad changes to define the revised format for tracks?  If so, I can try to conform to that and submit a PR for the update to render.js and the genericJSON schema (I'll leave the actual Kicad parser code to you)
![image](https://user-images.githubusercontent.com/24237058/109403195-8829e880-7929-11eb-8b8f-984bb5df2a76.png)

**Comment by qu1ck** [comment]
Yes, arcs will be defined exactly like you describe. They are not accessible from python yet but I sent a MR for that
https://gitlab.com/kicad/code/kicad/-/merge_requests/701

**Comment by Funkenjaeger** [comment]
Submitted PR #230
