### ISSUE TITLE
Do not mount parts

### ISSUE THREAD

**Issue by leoheck** [openscopeproject/InteractiveHtmlBom#231]
My board has DNM (do not mount) components tagged on the Schematic. 
Do we have any way to avoid these components when creating the interactive BOM?

Or add a column with a DNM tag or use a gray color on the list or something that makes these different than the components that have to be installed?

**Comment by iharshadec** [comment]
This is interesting. I used to place DNP - Do not Place lable and yes if we get some indication that would be really great.

**Comment by leoheck** [comment]
Yeah, a field with a custom label would be nice, so you could use the DNP and I DNM. 
I have this custom BOM script that generates a simple bom.csv.
This one does not include components that do not have a footprint or MPN (manufacture part number). It also filters out components with DNM tags.
So, if we could have something that does the same for the Interactive BOM, it would be awesome.

**Comment by qu1ck** [comment]
![image](https://user-images.githubusercontent.com/3622532/109543318-f92ce580-7a7a-11eb-95c1-ccf696df77f9.png)

**Comment by leoheck** [comment]
Oh, @qu1ck thank you so much, I am dumb.
