### ISSUE TITLE
InteractiveHtmlBom and KiCad 6

### ISSUE THREAD

**Issue by ericNantes** [openscopeproject/InteractiveHtmlBom#232]
Hi,
I've been using InteractiveHtmlBom since a long time now in my classroom.
KiCad 6 is coming soon and I often try the nightly build. Files PCBnew format have changed and the plugin doesn't work anymore.
Are you going to update your plugin for this new KiCad version ?
Regards.
Eric

**Comment by qu1ck** [comment]
I make nightly compatibility fixes all the time.

https://github.com/openscopeproject/InteractiveHtmlBom/wiki/FAQ#q-i-am-using-kicad-nightly-build-and-plugin-doesnt-work
