### ISSUE TITLE
New KiCad v6 incompatibilities

### ISSUE THREAD

**Issue by rainer38** [openscopeproject/InteractiveHtmlBom#235]
I'm using a self-compiled newer KiCad Version v5.99 and it seems something in the Python API has changed. First change seems to be in the function pcbnew.ExpandTextVars() which now has three instead of two options. I found three references in ecad/kicad.py which seems optional and i just commented them. After that the Script runs without exceptions and the generated html has all the control elements but no components nor the board.

I know that my KiCad version is not the latest release version but KiCad v6 is on the road to be released and has really usefull features i don't want to miss anymore.

So maybe you can give me some hint where i can look into to get the script fixed for the upcoming version. :)

**Comment by qu1ck** [comment]
When you use nightly Kicad version you also need nightly/latest version of plugin from master branch which works fine.
