### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by dotneck335** [openscopeproject/InteractiveHtmlBom#240]
Got it installed---put InteractiveHTMLBom in AppData/Roaming/kicad/scripting/plugins. Opened pcbnew, refreshed plugins, got icon on menu bar. Clicked on it, and got the menu for options, clicked on 'save current settings' and 'Generate BOM'. Got an Internet Explorer page with a screen that looks like a form with no entries--no data whatsoever. Warning at bottom about "restricted this website from running scripts or ActiveX controls". Clicked on 'Allow blocked content'.
NO HELP--- Still a form with no data entries.
???????

**Comment by qu1ck** [comment]
https://github.com/openscopeproject/InteractiveHtmlBom/wiki/FAQ#q-generated-bom-page-doesnt-work-in-ieoperanetscapesamsung-browserkindlemy-microwave-that-can-run-doom-3d

**Comment by qu1ck** [comment]
To clarify, open the generated page in a modern browser (chrome, firefox, edge, safari). IE is not supported and will not be supported.
If you have a modern browser installed but plugin still opens IE then make sure your browser is set as default to handle html files in your OS.

**Comment by dotneck335** [comment]
Thanks! That did it! How do I set my normal browser (firefox) as default to
open html files?

**Comment by dotneck335** [comment]
Never mind! Found default settings and changed default browser and .html opener to Firefox,
