### ISSUE TITLE
Get extra fields from footprint.GetProperties()

### ISSUE THREAD

**Issue by arturo182** [openscopeproject/InteractiveHtmlBom#241]
I'm not sure if it's possible with how KiCad files are structured but since usually whole blocks are separated into hierarchical sheets in the schematic, it would be a nice feature to be able to filter by sheets in ibom. 
This way you could assemble boards sheet by sheet and test each block as you go. It's a very specific feature and maybe it wouldn't be usable to that many, but thought I'll propose it anyway on the off chance you think it's useful too ;)

**Comment by qu1ck** [comment]
This will automatically work in v6 when I implement getting extra fields from pcb file as original schematic sheet is stored on footprint properties.
Then you will be able to use sheet as extra field and use standard filtering/sorting controls.

But I won't promise to backport this to 5.1

**Comment by arturo182** [comment]
Awesome! And I don't mind nightly only, been living that #nightlylife for years now :)

Should I close the issue then?

**Comment by qu1ck** [comment]
Nah, let's repurpose this one to track parsing extra fields from pcb file so that I don't forget.

**Comment by sticilface** [comment]
I’d like to filter by hierarchical sheet as well. Is this a feature that will work with kicad 6 but not 5.1? If I understand correctly.

**Comment by qu1ck** [comment]
You understand correctly. But it's not implemented yet.
