### ISSUE TITLE
No attribute "GetFootprintRect" found

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [openscopeproject/InteractiveHtmlBom#242]
Open any (place footpritn from stock library and draw rectangle on edge.cuts) board with most recent kicad nightly, try to use iBom, get an error:

![image](https://user-images.githubusercontent.com/46539653/114674146-984a2b80-9d0f-11eb-9f6f-f6185b17e4d4.png)

iBOM version: "v2.3";

kicad version:
Application: KiCad PCB Editor

Version: (5.99.0-10287-gf7cc6d1e1e), release build

Libraries:
	wxWidgets 3.1.4
	libcurl/7.74.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19042), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Apr 13 2021 12:06:17
	wxWidgets: 3.1.4 (wchar_t,STL containers)
	Boost: 1.75.0
	OCC: 7.5.0
	Curl: 7.74.0-DEV
	ngspice: 34
	Compiler: Visual C++ 1928 without C++ ABI

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=ON
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
	KICAD_SCRIPTING_ACTION_MENU=ON
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by qu1ck** [comment]
When using kicad nightly you need to use development version of the plugin from master branch.

https://github.com/openscopeproject/InteractiveHtmlBom/wiki/FAQ#q-i-am-using-kicad-nightly-build-and-plugin-doesnt-work
