### ISSUE TITLE
Exception with kicad v5.99

### ISSUE THREAD

**Issue by chopin1998** [openscopeproject/InteractiveHtmlBom#244]
![image](https://user-images.githubusercontent.com/643792/115663088-818c8000-a372-11eb-9005-ebd380bd4315.png)

**Comment by qu1ck** [comment]
People don't read the FAQ, I guess I'll have to keep one issue about this open until v6 is released.

Use latest version of plugin from master branch if you are using nightly.

**Comment by chopin1998** [comment]
sorry.... and thank thee very much!

**Comment by arturo182** [comment]
@qu1ck I have notifications enabled for new issues in this repo and I admire your patience 🙏

**Comment by blopblopblup** [comment]
Sorry to bring it up again, I do have an exception with 5.99 and the latest pull from master. 
![traceback](https://user-images.githubusercontent.com/18424855/126637102-cd6ac3b2-d322-4f36-a2ab-1d44cfc63755.png)

**Comment by tistructor** [comment]
I installed kicad's latest nightly and master plugin but I get this error window:
<img width="418" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/137620661-c24f67d6-452e-420c-b9a6-60a67dcc17c7.PNG">

**Comment by qu1ck** [comment]
I have no idea how that error can happen. It complains that wx has no grid attribute which is actually a submodule and it is imported in that same file. If it couldn't find the submodule it should have complained on import, not later when it's used.

Can you try opening scripting console and pasting this line by line:
```
import wx.grid
g = wx.grid.Grid()
dir(g)
```

**Comment by tistructor** [comment]
['AcceleratorTable', 'AcceptsFocus', 'AcceptsFocusFromKeyboard', 'AcceptsFocusRecursively', 'AddChild', 'AddFilter', 'AddPendingEvent', 'AdjustForLayoutDirection', 'AdjustScrollbars', 'AlwaysShowScrollbars', 'AppendCols', 'AppendRows', 'AreHorzGridLinesClipped', 'AreVertGridLinesClipped', 'AssignTable', 'AssociateHandle', 'AutoLayout', 'AutoSize', 'AutoSizeColLabelSize', 'AutoSizeColumn', 'AutoSizeColumns', 'AutoSizeRow', 'AutoSizeRowLabelSize', 'AutoSizeRows', 'BackgroundColour', 'BackgroundStyle', 'BatchCount', 'BeginBatch', 'BeginRepositioningChildren', 'BestSize', 'BestVirtualSize', 'Bind', 'BlockToDeviceRect', 'Border', 'CacheBestSize', 'CalcCellsExposed', 'CalcColLabelsExposed', 'CalcGridWindowScrolledPosition', 'CalcGridWindowUnscrolledPosition', 'CalcRowLabelsExposed', 'CalcScrolledPosition', 'CalcUnscrolledPosition', 'CanAcceptFocus', 'CanAcceptFocusFromKeyboard', 'CanDragCell', 'CanDragColMove', 'CanDragColSize', 'CanDragGridColEdges', 'CanDragGridRowEdges', 'CanDragGridSize', 'CanDragRowSize', 'CanEnableCellControl', 'CanHaveAttributes', 'CanHideColumns', 'CanScroll', 'CanSetTransparent', 'CaptureMouse', 'Caret', 'CellHighlightColour', 'CellHighlightPenWidth', 'CellHighlightROPenWidth', 'CellSpan', 'CellSpan_Inside', 'CellSpan_Main', 'CellSpan_None', 'CellToGridWindow', 'CellToRect', 'Center', 'CenterOnParent', 'Centre', 'CentreOnParent', 'CharHeight', 'CharWidth', 'Children', 'ChildrenRepositioningGuard', 'ClassInfo', 'ClassName', 'ClearBackground', 'ClearGrid', 'ClearSelection', 'ClientAreaOrigin', 'ClientRect', 'ClientSize', 'ClientToScreen', 'ClientToWindowSize', 'ClipHorzGridLines', 'ClipVertGridLines', 'Close', 'ColLabelSize', 'ColLabelTextOrientation', 'ColMinimalAcceptableWidth', 'ColSizes', 'Connect', 'Constraints', 'ContainingSizer', 'ConvertDialogPointToPixels', 'ConvertDialogSizeToPixels', 'ConvertDialogToPixels', 'ConvertPixelsToDialog', 'CornerLabelTextOrientation', 'CornerLabelValue', 'Create', 'CreateGrid', 'Cursor', 'DLG_UNIT', 'DefaultAttributes', 'DefaultCellBackgroundColour', 'DefaultCellFitMode', 'DefaultCellFont', 'DefaultCellOverflow', 'DefaultCellTextColour', 'DefaultColLabelSize', 'DefaultColSize', 'DefaultEditor', 'DefaultGridLinePen', 'DefaultRenderer', 'DefaultRowLabelSize', 'DefaultRowSize', 'DeleteCols', 'DeletePendingEvents', 'DeleteRows', 'DeselectCell', 'DeselectCol', 'DeselectRow', 'Destroy', 'DestroyChildren', 'DestroyLater', 'DevicePosToGridWindow', 'Disable', 'DisableCellEditControl', 'DisableColResize', 'DisableDragColMove', 'DisableDragColSize', 'DisableDragGridSize', 'DisableDragRowSize', 'DisableFocusFromKeyboard', 'DisableHidingColumns', 'DisableKeyboardScrolling', 'DisableRowResize', 'Disconnect', 'DissociateHandle', 'DoEnable', 'DoFreeze', 'DoGetBestClientSize', 'DoGetBestSize', 'DoGetBorderSize', 'DoGetClientSize', 'DoGetPosition', 'DoGetSize', 'DoMoveWindow', 'DoPrepareDC', 'DoSetClientSize', 'DoSetSize', 'DoSetSizeHints', 'DoSetWindowVariant', 'DoThaw', 'DoUpdateWindowUI', 'DragAcceptFiles', 'DrawCellHighlight', 'DrawColLabel', 'DrawColLabels', 'DrawCornerLabel', 'DrawRowLabel', 'DrawRowLabels', 'DrawTextRectangle', 'DropTarget', 'EffectiveMinSize', 'Enable', 'EnableCellEditControl', 'EnableDragCell', 'EnableDragColMove', 'EnableDragColSize', 'EnableDragGridSize', 'EnableDragRowSize', 'EnableEditing', 'EnableGridLines', 'EnableHidingColumns', 'EnableScrolling', 'EnableTouchEvents', 'EnableVisibleFocus', 'Enabled', 'EndBatch', 'EndRepositioningChildren', 'EventHandler', 'EvtHandlerEnabled', 'ExtraStyle', 'FindFocus', 'FindWindow', 'FindWindowById', 'FindWindowByLabel', 'FindWindowByName', 'FirstFullyVisibleColumn', 'FirstFullyVisibleRow', 'Fit', 'FitInside', 'Font', 'ForceRefresh', 'ForegroundColour', 'Freeze', 'FreezeTo', 'FromDIP', 'FrozenColGridWindow', 'FrozenCornerGridWindow', 'FrozenRowGridWindow', 'GetAcceleratorTable', 'GetAccessible', 'GetAutoLayout', 'GetBackgroundColour', 'GetBackgroundStyle', 'GetBatchCount', 'GetBestHeight', 'GetBestSize', 'GetBestVirtualSize', 'GetBestWidth', 'GetBorder', 'GetCapture', 'GetCaret', 'GetCellAlignment', 'GetCellBackgroundColour', 'GetCellEditor', 'GetCellFitMode', 'GetCellFont', 'GetCellHighlightColour', 'GetCellHighlightPenWidth', 'GetCellHighlightROPenWidth', 'GetCellOverflow', 'GetCellRenderer', 'GetCellSize', 'GetCellTextColour', 'GetCellValue', 'GetCharHeight', 'GetCharWidth', 'GetChildren', 'GetClassDefaultAttributes', 'GetClassInfo', 'GetClassName', 'GetClientAreaOrigin', 'GetClientRect', 'GetClientSize', 'GetColAt', 'GetColGridLinePen', 'GetColLabelAlignment', 'GetColLabelSize', 'GetColLabelTextOrientation', 'GetColLabelValue', 'GetColLeft', 'GetColMinimalAcceptableWidth', 'GetColMinimalWidth', 'GetColPos', 'GetColRight', 'GetColSize', 'GetColSizes', 'GetConstraints', 'GetContainingSizer', 'GetContentScaleFactor', 'GetCornerLabelAlignment', 'GetCornerLabelTextOrientation', 'GetCornerLabelValue', 'GetCursor', 'GetDPI', 'GetDPIScaleFactor', 'GetDefaultAttributes', 'GetDefaultBorder', 'GetDefaultBorderForControl', 'GetDefaultCellAlignment', 'GetDefaultCellBackgroundColour', 'GetDefaultCellFitMode', 'GetDefaultCellFont', 'GetDefaultCellOverflow', 'GetDefaultCellTextColour', 'GetDefaultColLabelSize', 'GetDefaultColSize', 'GetDefaultEditor', 'GetDefaultEditorForCell', 'GetDefaultEditorForType', 'GetDefaultGridLinePen', 'GetDefaultRenderer', 'GetDefaultRendererForCell', 'GetDefaultRendererForType', 'GetDefaultRowLabelSize', 'GetDefaultRowSize', 'GetDropTarget', 'GetEffectiveMinSize', 'GetEventHandler', 'GetEvtHandlerEnabled', 'GetExtraStyle', 'GetFirstFullyVisibleColumn', 'GetFirstFullyVisibleRow', 'GetFont', 'GetForegroundColour', 'GetFrozenColGridWindow', 'GetFrozenCornerGridWindow', 'GetFrozenRowGridWindow', 'GetFullTextExtent', 'GetGrandParent', 'GetGridColHeader', 'GetGridColLabelWindow', 'GetGridCornerLabelWindow', 'GetGridCursorCol', 'GetGridCursorCoords', 'GetGridCursorRow', 'GetGridLineColour', 'GetGridRowLabelWindow', 'GetGridWindow', 'GetGridWindowOffset', 'GetGtkWidget', 'GetHandle', 'GetHelpText', 'GetHelpTextAtPoint', 'GetId', 'GetLabel', 'GetLabelBackgroundColour', 'GetLabelFont', 'GetLabelTextColour', 'GetLayoutDirection', 'GetMainWindowOfCompositeControl', 'GetMaxClientSize', 'GetMaxHeight', 'GetMaxSize', 'GetMaxWidth', 'GetMinClientSize', 'GetMinHeight', 'GetMinSize', 'GetMinWidth', 'GetName', 'GetNextHandler', 'GetNextSibling', 'GetNumberCols', 'GetNumberFrozenCols', 'GetNumberFrozenRows', 'GetNumberRows', 'GetOrCreateCellAttr', 'GetOrCreateCellAttrPtr', 'GetParent', 'GetPopupMenuSelectionFromUser', 'GetPosition', 'GetPositionTuple', 'GetPrevSibling', 'GetPreviousHandler', 'GetRect', 'GetRefData', 'GetRowGridLinePen', 'GetRowLabelAlignment', 'GetRowLabelSize', 'GetRowLabelValue', 'GetRowMinimalAcceptableHeight', 'GetRowMinimalHeight', 'GetRowSize', 'GetRowSizes', 'GetScaleX', 'GetScaleY', 'GetScreenPosition', 'GetScreenRect', 'GetScrollLineX', 'GetScrollLineY', 'GetScrollLines', 'GetScrollPageSize', 'GetScrollPixelsPerUnit', 'GetScrollPos', 'GetScrollRange', 'GetScrollThumb', 'GetSelectedBlocks', 'GetSelectedCells', 'GetSelectedColBlocks', 'GetSelectedCols', 'GetSelectedRowBlocks', 'GetSelectedRows', 'GetSelectionBackground', 'GetSelectionBlockBottomRight', 'GetSelectionBlockTopLeft', 'GetSelectionForeground', 'GetSelectionMode', 'GetSize', 'GetSizeAvailableForScrollTarget', 'GetSizeTuple', 'GetSizer', 'GetSortingColumn', 'GetTable', 'GetTargetRect', 'GetTargetWindow', 'GetTextExtent', 'GetThemeEnabled', 'GetToolTip', 'GetToolTipText', 'GetTopLevelParent', 'GetUpdateClientRect', 'GetUpdateRegion', 'GetValidator', 'GetViewStart', 'GetVirtualSize', 'GetVirtualSizeTuple', 'GetWindowBorderSize', 'GetWindowStyle', 'GetWindowStyleFlag', 'GetWindowVariant', 'GoToCell', 'GrandParent', 'GridColHeader', 'GridColLabelWindow', 'GridCornerLabelWindow', 'GridCursorCol', 'GridCursorCoords', 'GridCursorRow', 'GridLineColour', 'GridLinesEnabled', 'GridRowLabelWindow', 'GridSelectCells', 'GridSelectColumns', 'GridSelectNone', 'GridSelectRows', 'GridSelectRowsOrColumns', 'GridSelectionModes', 'GridWindow', 'Handle', 'HandleAsNavigationKey', 'HandleWindowEvent', 'HasCapture', 'HasExtraStyle', 'HasFlag', 'HasFocus', 'HasMultiplePages', 'HasScrollbar', 'HasTransparentBackground', 'HelpText', 'Hide', 'HideCellEditControl', 'HideCol', 'HideColLabels', 'HideRow', 'HideRowLabels', 'HideWithEffect', 'HitTest', 'Id', 'InformFirstDirection', 'InheritAttributes', 'InheritsBackgroundColour', 'InheritsForegroundColour', 'InitDialog', 'InsertCols', 'InsertRows', 'InvalidateBestSize', 'IsAutoScrolling', 'IsBeingDeleted', 'IsCellEditControlEnabled', 'IsCellEditControlShown', 'IsColShown', 'IsCurrentCellReadOnly', 'IsDescendant', 'IsDoubleBuffered', 'IsEditable', 'IsEnabled', 'IsExposed', 'IsFocusable', 'IsFrozen', 'IsInSelection', 'IsReadOnly', 'IsRetained', 'IsRowShown', 'IsSameAs', 'IsScrollbarAlwaysShown', 'IsSelection', 'IsShown', 'IsShownOnScreen', 'IsSortOrderAscending', 'IsSortingBy', 'IsThisEnabled', 'IsTopLevel', 'IsTransparentBackgroundSupported', 'IsUnlinked', 'IsUsingNativeHeader', 'IsVisible', 'Label', 'LabelBackgroundColour', 'LabelFont', 'LabelTextColour', 'Layout', 'LayoutDirection', 'LineDown', 'LineUp', 'Lower', 'MacIsWindowScrollbar', 'MakeCellVisible', 'MaxClientSize', 'MaxHeight', 'MaxSize', 'MaxWidth', 'MinClientSize', 'MinHeight', 'MinSize', 'MinWidth', 'Move', 'MoveAfterInTabOrder', 'MoveBeforeInTabOrder', 'MoveCursorDown', 'MoveCursorDownBlock', 'MoveCursorLeft', 'MoveCursorLeftBlock', 'MoveCursorRight', 'MoveCursorRightBlock', 'MoveCursorUp', 'MoveCursorUpBlock', 'MovePageDown', 'MovePageUp', 'MoveXY', 'Name', 'Navigate', 'NavigateIn', 'NewControlId', 'NextHandler', 'NumberCols', 'NumberFrozenCols', 'NumberFrozenRows', 'NumberRows', 'OnDraw', 'OnInternalIdle', 'PageDown', 'PageUp', 'Parent', 'PopEventHandler', 'PopupMenu', 'Position', 'PostCreate', 'PostSizeEvent', 'PostSizeEventToParent', 'PrepareDC', 'PreviousHandler', 'ProcessEvent', 'ProcessEventLocally', 'ProcessPendingEvents', 'ProcessTableMessage', 'ProcessWindowEvent', 'ProcessWindowEventLocally', 'PushEventHandler', 'QueueEvent', 'Raise', 'Rect', 'Ref', 'RefData', 'Refresh', 'RefreshAttr', 'RefreshRect', 'RegisterDataType', 'RegisterHotKey', 'ReleaseMouse', 'RemoveChild', 'RemoveEventHandler', 'RemoveFilter', 'Render', 'Reparent', 'ResetColPos', 'RowLabelSize', 'RowMinimalAcceptableHeight', 'RowSizes', 'SafelyProcessEvent', 'SaveEditControlValue', 'ScaleX', 'ScaleY', 'ScreenPosition', 'ScreenRect', 'ScreenToClient', 'Scroll', 'ScrollLineX', 'ScrollLineY', 'ScrollLines', 'ScrollPages', 'ScrollWindow', 'SelectAll', 'SelectBlock', 'SelectCells', 'SelectCol', 'SelectColumns', 'SelectRow', 'SelectRows', 'SelectRowsOrColumns', 'SelectedBlocks', 'SelectedCells', 'SelectedColBlocks', 'SelectedCols', 'SelectedRowBlocks', 'SelectedRows', 'SelectionBackground', 'SelectionBlockBottomRight', 'SelectionBlockTopLeft', 'SelectionForeground', 'SelectionMode', 'SendAutoScrollEvents', 'SendDestroyEvent', 'SendIdleEvents', 'SendSizeEvent', 'SendSizeEventToParent', 'SetAcceleratorTable', 'SetAccessible', 'SetAttr', 'SetAutoLayout', 'SetBackgroundColour', 'SetBackgroundStyle', 'SetCanFocus', 'SetCaret', 'SetCellAlignment', 'SetCellBackgroundColour', 'SetCellEditor', 'SetCellFitMode', 'SetCellFont', 'SetCellHighlightColour', 'SetCellHighlightPenWidth', 'SetCellHighlightROPenWidth', 'SetCellOverflow', 'SetCellRenderer', 'SetCellSize', 'SetCellTextColour', 'SetCellValue', 'SetClientRect', 'SetClientSize', 'SetColAttr', 'SetColFormatBool', 'SetColFormatCustom', 'SetColFormatDate', 'SetColFormatFloat', 'SetColFormatNumber', 'SetColLabelAlignment', 'SetColLabelSize', 'SetColLabelTextOrientation', 'SetColLabelValue', 'SetColMinimalAcceptableWidth', 'SetColMinimalWidth', 'SetColPos', 'SetColSize', 'SetColSizes', 'SetColumnsOrder', 'SetConstraints', 'SetContainingSizer', 'SetCornerLabelAlignment', 'SetCornerLabelTextOrientation', 'SetCornerLabelValue', 'SetCursor', 'SetDefaultCellAlignment', 'SetDefaultCellBackgroundColour', 'SetDefaultCellFitMode', 'SetDefaultCellFont', 'SetDefaultCellOverflow', 'SetDefaultCellTextColour', 'SetDefaultColSize', 'SetDefaultEditor', 'SetDefaultRenderer', 'SetDefaultRowSize', 'SetDimensions', 'SetDoubleBuffered', 'SetDropTarget', 'SetEventHandler', 'SetEvtHandlerEnabled', 'SetExtraStyle', 'SetFocus', 'SetFocusFromKbd', 'SetFont', 'SetForegroundColour', 'SetGridCursor', 'SetGridFrozenBorderColour', 'SetGridFrozenBorderPenWidth', 'SetGridLineColour', 'SetHelpText', 'SetId', 'SetInitialSize', 'SetLabel', 'SetLabelBackgroundColour', 'SetLabelFont', 'SetLabelTextColour', 'SetLayoutDirection', 'SetMargins', 'SetMaxClientSize', 'SetMaxSize', 'SetMinClientSize', 'SetMinSize', 'SetName', 'SetNextHandler', 'SetOwnBackgroundColour', 'SetOwnFont', 'SetOwnForegroundColour', 'SetPalette', 'SetPosition', 'SetPreviousHandler', 'SetReadOnly', 'SetRect', 'SetRefData', 'SetRowAttr', 'SetRowLabelAlignment', 'SetRowLabelSize', 'SetRowLabelValue', 'SetRowMinimalAcceptableHeight', 'SetRowMinimalHeight', 'SetRowSize', 'SetRowSizes', 'SetScale', 'SetScrollLineX', 'SetScrollLineY', 'SetScrollPageSize', 'SetScrollPos', 'SetScrollRate', 'SetScrollbar', 'SetScrollbars', 'SetSelectionBackground', 'SetSelectionForeground', 'SetSelectionMode', 'SetSize', 'SetSizeHints', 'SetSizeHintsSz', 'SetSizeWH', 'SetSizer', 'SetSizerAndFit', 'SetSortingColumn', 'SetTabBehaviour', 'SetTable', 'SetTargetRect', 'SetTargetWindow', 'SetThemeEnabled', 'SetToolTip', 'SetToolTipString', 'SetTransparent', 'SetUseNativeColLabels', 'SetValidator', 'SetVirtualSize', 'SetVirtualSizeWH', 'SetWindowStyle', 'SetWindowStyleFlag', 'SetWindowVariant', 'ShouldInheritColours', 'ShouldScrollToChildOnFocus', 'Show', 'ShowCellEditControl', 'ShowCol', 'ShowRow', 'ShowScrollbars', 'ShowWithEffect', 'Shown', 'Size', 'Sizer', 'SortingColumn', 'StopAutoScrolling', 'TabBehaviour', 'Tab_Leave', 'Tab_Stop', 'Tab_Wrap', 'Table', 'TargetRect', 'TargetWindow', 'Thaw', 'ThemeEnabled', 'ToDIP', 'ToggleWindowStyle', 'ToolTip', 'TopLevel', 'TopLevelParent', 'TransferDataFromWindow', 'TransferDataToWindow', 'TryAfter', 'TryBefore', 'UnRef', 'UnShare', 'Unbind', 'Unlink', 'UnregisterHotKey', 'UnreserveControlId', 'UnsetSortingColumn', 'UnsetToolTip', 'Update', 'UpdateClientRect', 'UpdateRegion', 'UpdateWindowUI', 'UseBackgroundColour', 'UseBgCol', 'UseForegroundColour', 'UseNativeColHeader', 'Validate', 'Validator', 'VirtualSize', 'WarpPointer', 'WindowStyle', 'WindowStyleFlag', 'WindowToClientSize', 'WindowVariant', 'XToCol', 'XToEdgeOfCol', 'XYToCell', 'YToEdgeOfRow', 'YToRow', '_SetTable', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']

**Comment by tistructor** [comment]
Thanks,
Will I have to wait for new builds to try the plugin?

**Comment by qu1ck** [comment]
Either that or patch the diff I linked and build yourself :)

**Comment by qu1ck** [comment]
Should be fixed in 25c088b but you will need to get newer kicad nightly as well.

**Comment by sborshch** [comment]
KiCad 6.0.0-rc1-160-g99ec2b1801 (today's git master)
InteractiveHtmlBom cloned as git clone https://github.com/openscopeproject/InteractiveHtmlBom.git (today's master)

got error "AttributeError: 'FP_SHAPE' object has no attribute 'GetAngle'"

**Comment by qu1ck** [comment]
Now that v6 is released this issue is obsolete.
