### ISSUE TITLE
Unable to render in Safari

### ISSUE THREAD

**Issue by Gasman2014** [openscopeproject/InteractiveHtmlBom#25]
Previously able to render OK in Safari but a recent change has now broken that. 

Board details are not available in the header and the board does not initially appear but will do so when the window is resized. The BOM table is empty. The board area will zoom and pan OK once activated by resizing the parent window but this still does not trigger loading of the BOM list or header details.

The exact same html file loads and behaves normally in Chrome.

**Comment by qu1ck** [comment]
Safari has same issue as Edge: they don't allow access to localStorage from file:// protocol pages. A position which is different from one Chrome and FF took, however not without merit.

I suppose I could add fallback to sessionStorage for these browsers. Your settings and checkboxes will be lost on browser restart though.
