### ISSUE TITLE
Feature Request: Focus on the selected components

### ISSUE THREAD

**Issue by mdeweerd** [openscopeproject/InteractiveHtmlBom#250]
Version: 2.3

Currently, when selecting components that are not in view, the viewport do not adjust (shift) to the selected components.

I suggest:
- No click: current behavior, only highlight;
- Single click: keep the line selected to keep the component(s) hightlighted even when the mouse is no longer hovering the line in the list.
- Multiple selected components (CTRL+click to add, CTRL+SHIFT+CLICK to mark end of a list): multiple lines can be selected to highlight all components (involved);
- Double click: adjust the viewport to the components selected by the line (possibly add an option to set the maximum zoom level for this function).

**Comment by qu1ck** [comment]
Auto zoom was also discussed in #246.
Multiple selection is planned as part of #206 where you will be able to "permanently" highlight some rows.

**Comment by mdeweerd** [comment]
Thank your for the feedback.

It was difficult to tell from the time/initial message for the abovementioned items.  I try to keep one feature per "Issue". ;-).

**Comment by mdeweerd** [comment]
Stale Issue, closed by the author, not a bot ;-).
