### ISSUE TITLE
Slight misalignment of text.

### ISSUE THREAD

**Issue by phil-barrett** [openscopeproject/InteractiveHtmlBom#251]
This is a fantastic piece of work.

I noticed on my board that some text is not correctly aligned in the board view.  I have a number of fields that are aligned via Align/Distribute so they show up as aligned in KiCad, gerb view, OSHPark's viewer and, more importantly, on the actual PCB.  Gnd, SPD and SPE in the screens shots are center justified text fields and others are left. Yet they show up with different Y values in iBOM. Not the end of the world but thought you would want to know. I can't share the Kicad files with you, sorry.

![image](https://user-images.githubusercontent.com/16570958/120734893-7f9ffb80-c49e-11eb-92c2-118f852387c3.png)
![image](https://user-images.githubusercontent.com/16570958/120734997-a78f5f00-c49e-11eb-8fbd-70e1079573c5.png)

**Comment by qu1ck** [comment]
I think this was fixed in 6c70a9d576a2a633b733d41643f6015329f37087

Can you try with latest ibom from master?

If the issue persists please copy paste that connector with surrounding text into an empty pcb, there should be no issues with sharing that.

**Comment by phil-barrett** [comment]
Sure, is that V2.3?

**Comment by qu1ck** [comment]
No, it's not in any release yet, use

![image](https://user-images.githubusercontent.com/3622532/120737728-76655d80-c4a3-11eb-954f-97a9a115d1d7.png)

direct link: https://github.com/openscopeproject/InteractiveHtmlBom/archive/refs/heads/master.zip

**Comment by phil-barrett** [comment]
Yes, that also fixes it. I will close the issue.  Thanks for the quick response!
