### ISSUE TITLE
Uncaught DOMException when extra fields contain spaces

### ISSUE THREAD

**Issue by cdwilson** [openscopeproject/InteractiveHtmlBom#253]
When I include an extra field which contains spaces in the field name, the BOM fails to load and I get the following error:

```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('Manufacturer Part Number') contains HTML space characters, which are not valid in tokens.
```

![image](https://user-images.githubusercontent.com/14631/121793927-b241a680-cbb8-11eb-9a24-5805a181524c.png)

![image](https://user-images.githubusercontent.com/14631/121793908-8d4d3380-cbb8-11eb-9bb6-c1ccb8fe21b2.png)

**Comment by qu1ck** [comment]
Thanks for testing the dev branch and reporting bugs!

**Comment by cdwilson** [comment]
Thanks for the quick fix!
