### ISSUE TITLE
Non-filled rectangles in EasyEDA dont render properly

### ISSUE THREAD

**Issue by EdHayes3** [openscopeproject/InteractiveHtmlBom#258]
I have a non-filled rectangle in EasyEDA.

I believe the Json for the object is:
`RECT~4452~3145~157.48~157.48~3~gge7857~0~1~none~~TEST~`

Two problems with it. 

1. The position is incorrect. Should be to the right in the big blank space. 
2. It's showing filled in. Should be just an outline.

Output:
![image](https://user-images.githubusercontent.com/74882458/124662400-678d1480-de6e-11eb-970e-f5abb76d30dc.png)

EasyEDA Object:
<img width="1944" alt="Screen Shot 2021-07-06 at 3 29 01 PM, Jul 6" src="https://user-images.githubusercontent.com/74882458/124662931-0b76c000-de6f-11eb-9e1d-8fec29fac8a4.png">

**Comment by qu1ck** [comment]
Thanks for the bug report. I do wish easyeda kept their docs up to date, it's not the first time they have something undocumented in their files...

**Comment by EdHayes3** [comment]
Wow! that was quick! When should I expect the published version with this fix? I'm pretty new to this github thing...

And re: undocumented items... At least it's not like Oracle.. they specifically document something in one way (functionality which makes sense, like 2+2=4), then the user finds there's a bug in the code (which is obvious, like 2+2 = 5), and they will claim it's a documentation bug. ha!

**Comment by qu1ck** [comment]
I don't plan publishing a new version soon, there will be one closer to kicad 6 launch but that's ways off.

You can always get latest from master branch from this link
https://github.com/openscopeproject/InteractiveHtmlBom/archive/refs/heads/master.zip

or by going to project page, clicking code -> download zip

![image](https://user-images.githubusercontent.com/3622532/124700046-daaf7e80-dea0-11eb-81cd-6aae7533a778.png)

> At least it's not like Oracle.. they specifically document something in one way (functionality which makes sense, like 2+2=4), then the user finds there's a bug in the code (which is obvious, like 2+2 = 5), and they will claim it's a documentation bug. ha!

That's funny. Easyeda are just being lazy and haven't updated docs in years while they've been adding features.
