### ISSUE TITLE
KiCAD-nightly (versions since ~6 weeks) do not show vias on bottom-side

### ISSUE THREAD

**Issue by DDuck007** [openscopeproject/InteractiveHtmlBom#264]
Using latest nightlies of Kicad and using InteractiveHtmlBom does not show vias on bottom side when tracks are enabled - see picture attached. On top-side everything is ok.
![grafik](https://user-images.githubusercontent.com/54204584/127019917-b04170a8-c393-48b1-8c6f-d067110743b2.png)

**Comment by qu1ck** [comment]
For arcs see also related merge request on kicad https://gitlab.com/kicad/code/kicad/-/merge_requests/897
Arcs will cause an error until that is merged and you update your nightly.
