### ISSUE TITLE
Add "Reset" function 

### ISSUE THREAD

**Issue by VanDerSnow** [openscopeproject/InteractiveHtmlBom#265]
Once you make any changes in viewer or settings, it would be nice to have "Reset" function.

Suggested reset functions:
1. "Restore defaults" in "Settings" drop down menu
2. "Reset view" in PCB board viewer to return to default view
3. "Reset table" in table list to clear any ticks

**Comment by qu1ck** [comment]
I don't see a lot of value in this
1. You can just switch them back, there are not a lot of them
2. RIght click on board viewer resets it. Or just reload the page.
3. Double click on checkbox column header sets/unsets all checkboxes in that column.
