### ISSUE TITLE
Export/Import settings with same Folder as BOM-Location

### ISSUE THREAD

**Issue by hintiflo** [openscopeproject/InteractiveHtmlBom#266]
When Exporting/Importing JSON Files with the Settings, i would be convinient, if this would start in the same directory as the current location of the BOM File.
We usually make separate Setting-JSONs for every single Batch or Board to be produced in order to keep Track of their status and therefore store them next ot the according BOM-html.
Its a bit clumsy to navigate through the Folder-Structure everytime and would save time, if it already suggests to store it in mentioned location.
Even better: Allow to name the resulting JSON with a "Save as" dialouge!

**Comment by qu1ck** [comment]
This is not technically feasible, there is no javascript API to do this. It will be possible when https://wicg.github.io/file-system-access/ is accepted and widely supported but it can be years until that happens.

Until then the only thing ibom can do is generate a data blob and let browser "download" it. Whether you get a "Save as" dialog depends on your browsers download settings. For example in Chrome you can choose to have it show a dialog for every file or always save to a specific directory without asking.
