### ISSUE TITLE
Feature Request: Intelligent value matching

### ISSUE THREAD

**Issue by joelsa** [openscopeproject/InteractiveHtmlBom#270]
Sometimes my iBOM looks a bit like this:

![132831409-a4c0a967-6b0f-4b29-9ed7-f2a19ad162b6](https://user-images.githubusercontent.com/11414863/132848907-fc9a38ae-2515-4e5d-b8ca-f6848dc076d9.jpg)

One reason for this is that I am trying to reuse subschematics which often were created by other people quite some time ago.
The obvious, tedious fix is to implement and enforce a project-wide naming policy and correct it for all earlier revisions.

The intelligent and definitely faster way is to have some sort of matching among different phrasings of the same value.

Similar to how https://github.com/SchrodingersGat/KiBoM supports intelligent value matching:

![132836391-490610c8-9b79-420c-ab83-7ac17715146d](https://user-images.githubusercontent.com/11414863/132849141-163b653f-302c-4b21-80c3-2a1a7d83165d.jpeg)

The implementation is not that complicated:
https://github.com/SchrodingersGat/KiBoM/blob/master/kibom/units.py

I would like to implement it, if you agree that such a feature is useful.

**Comment by qu1ck** [comment]
This has been in ibom from the start pretty much

https://github.com/openscopeproject/InteractiveHtmlBom/blob/master/InteractiveHtmlBom/core/units.py#L3

But on your screenshot rows 11, 13 and 14 should have been combined so looks like there is some edge case here. Can you copy paste the table in text format or at least just those rows?

**Comment by qu1ck** [comment]
Probably just variation of mu character

https://www.compart.com/en/unicode/U+03BC

**Comment by joelsa** [comment]
> This has been in ibom from the start pretty much

Well, this is embarrassing. I just assumed it is not, because it did not work here,  but I should have checked the actual code instead.

Here you go:

 | Row  | Reference  | Value 
-- | -- | --
11 | C3425, C3429, C3432 | 1µ 
13 | C2306 | 1µF
14 | C2702 | 1u

So yeah, we have both https://www.compart.com/en/unicode/U+00B5 and https://www.compart.com/en/unicode/U+03BC Interestingly, the former is generated when using the [Compose Key] followed by [M] and [U] on Ubuntu, whereas the latter is the result of pressing [Alt Gr] + [M] on a German Keyboard. Only the latter is currently inside `units.py`.

**Comment by joelsa** [comment]
This was fixed in KiBom recently: https://github.com/SchrodingersGat/KiBoM/commit/d9c6eb11c0663216d89cd423de716006c3f94292

**Comment by qu1ck** [comment]
Fixed in 202aabff2e6085113b44a167c8e29dc31790a713
