### ISSUE TITLE
Toolbar icon size

### ISSUE THREAD

**Issue by leoheck** [openscopeproject/InteractiveHtmlBom#279]
Hi, nice that this thing is already on PCM. 

Now, the icon looks bigger than the others

![image](https://user-images.githubusercontent.com/1277920/142295997-0d83dbea-1f33-43fd-ad58-2b55e7ce013d.png)

I posted the same in the forum asking if we have any guidelines for this. 
https://forum.kicad.info/t/guideline-for-plugins/32036

**Comment by Gasman2014** [comment]
Think the guidelines suggest 24px x 24px - can't find the ref right now.

**Comment by leoheck** [comment]
I think it was 24px and it was reduced to 22px later.

**Comment by qu1ck** [comment]
It's 24x24. https://dev-docs.kicad.org/en/python/pcbnew/

**Comment by leoheck** [comment]
So, if you are following guidelines with 24px it shows the guideline is clearly wrong. Look at the image above dude.

**Comment by qu1ck** [comment]
I never said I am following current guideline. It used to be 32 because I wrote the first guideline. It was then reduced to 26 and now to 24.

**Comment by leoheck** [comment]
Ah, cool. So the issue still stands.

**Comment by leoheck** [comment]
Do you accept a PR? I can fix it if needed.

**Comment by leoheck** [comment]
Here is my attempt to help.
https://github.com/openscopeproject/InteractiveHtmlBom/pull/285
