### ISSUE TITLE
Problem with alignment targets

### ISSUE THREAD

**Issue by jp-ricaud** [openscopeproject/InteractiveHtmlBom#28]
Hi,

It seems that InteractiveHtmlBom is not able to process the file if alignment targets are placed on the Edge.Cuts layer:

```
c:\Program Files\KiCad\lib\python2.7\site-packages\wx-3.0-msw/wx/_core.py:16633:
 UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Loading c:\Program Files\KiCad\share\kicad\demos\sonde xilinx\test.kicad_pcb
Unsupported drawing class  PCB_TARGET
Unsupported drawing class  PCB_TARGET
Unsupported drawing class  PCB_TARGET
Dumping pcb json data
```

If the targets are removed, it works fine.

![kicad_target](https://user-images.githubusercontent.com/1943160/43834833-ec1c6f02-9b0f-11e8-9e3d-a7b8cb6ac87b.png)

**Comment by qu1ck** [comment]
It should just skip unsupported things. Are you sure bom was not generayed? Also you either didnt copy full log or you are using old version, please update to latest.

**Comment by qu1ck** [comment]
Also it could be that you are trying to generate bom in program files which needs elevated priveleges. Try copying board file to normal directory.

**Comment by qu1ck** [comment]
Bug confirmed, fix coming shortly.
