### ISSUE TITLE
how to populate the <company> tag when using Funkenjaeger's ulp script to generate the json file

### ISSUE THREAD

**Issue by Harry-ei6ku** [openscopeproject/InteractiveHtmlBom#281]
I'm trying to populate the "company" tag when using a json file generated by the eagle ulp, is there an easy fix? I'm a novice programmer so any pointers appreciated.

Harry

**Comment by qu1ck** [comment]
You should ask this in eagle ulp project repo: https://github.com/Funkenjaeger/brd2json/issues

I don't know if eagle captures that in the board file.
