### ISSUE TITLE
[Feature Request] Import copied BOM

### ISSUE THREAD

**Issue by JacobChrist** [openscopeproject/InteractiveHtmlBom#284]
I work in two different rooms with two different computers.  It would be nice to be able to copy the state of the BOM and paste it into a file or e-mail that can be imported into another browser with the state of the sourced and placed check boxes.

**Comment by qu1ck** [comment]
Implemented already

![image](https://user-images.githubusercontent.com/3622532/149639653-2e4d7e3f-a36b-47ad-87a3-263ec741ca28.png)

**Comment by JacobChrist** [comment]
Sweet!  I guess I have a reason to upgrade.
