### ISSUE TITLE
trouble installing the plugin

### ISSUE THREAD

**Issue by renegadecitizen** [openscopeproject/InteractiveHtmlBom#287]
i have version 6 of kicad
i have installed both though the plugin manager and file system
but the plugin wont showup
can u please help me?

**Comment by qu1ck** [comment]
Don't install both through plugin manager and file system. In v6 plugin manager is the recommended option.

So first, delete any files you manually copied.

Then restart kicad and check if the plugin shows up in pcb editor.

If it doesn't then go to action plugin preferences in pcb editor

![image](https://user-images.githubusercontent.com/3622532/158493908-3a1d60d1-7180-4d19-a06d-eaa95c84bc40.png)

If you have issues with plugin loading there will be a button with yellow warning sign at the bottom. Click it and show me a screenshot (or copy paste text) of that window.

**Comment by renegadecitizen** [comment]
Thanks for helping man
It still isn’t working
Here’s a screenshot
<img width="1440" alt="Screen Shot 2022-03-16 at 10 18 01 AM" src="https://user-images.githubusercontent.com/6202311/158637750-c6790b04-1a50-410c-b5ca-1cb87c3ff3e5.png">

**Comment by qu1ck** [comment]
Judging by the scrollbar there's a lot of errors, please copy paste whole text.

Also what is exact os version and kicad version? Is this M1 mac? Does the scripting console open without errors? It's the right most button on the top toolbar of the pcb editor.

**Comment by renegadecitizen** [comment]
https://pastebin.com/BPupiXnY

**Comment by qu1ck** [comment]
This is KiCad issue, similar one was reported earlier https://gitlab.com/kicad/code/kicad/-/issues/8622#note_689417072

There is also a workaround mentioned there to increase ulimit to > 256 but I don't have a mac and can't provide exact instructions so you'll have to figure that out yourself.

**Comment by renegadecitizen** [comment]
Thanks for your help

**Comment by qu1ck** [comment]
I got a response on the bug I linked above, this may also be caused with some notarization issues that should be fixed in 6.0.4. Try that release

**Comment by renegadecitizen** [comment]
Ok thanks
