### ISSUE TITLE
PCBs with empty edge cuts layer fail silently

### ISSUE THREAD

**Issue by poeschlr** [openscopeproject/InteractiveHtmlBom#29]
While investigating #27 i discovered that no BOM is created if the edge cuts layer is completely empty. But there is also no error message created.
As soon as there is at least one graphical element (example a line) on the edge cuts layer the BOM is created. (So it seems it can handle outlines that are not closed.)

**Comment by qu1ck** [comment]
Yeah plugin doesn't care about closed outlines, it just needs some point of reference to determine scale of the board for auto zooming. It uses combined bounding box of all edge cuts for that, but if there are none, bounding box is also not defined.
