### ISSUE TITLE
How can I get ibom to show surface mount components only?

### ISSUE THREAD

**Issue by Khalinda** [openscopeproject/InteractiveHtmlBom#290]
I don't know about anybody else, but I never populate through hole components when I'm populating surface mount components on a board.  I thought that that was normal.  The through-hole components are a distraction when I'm placing surface mount components.  Is there any way to get ibom to filter out through-hole components from the displayed BOM?

**Comment by qu1ck** [comment]
You can do it if you add a custom field to the symbols to indicate smt/tht and include it in bom.

**Comment by Khalinda** [comment]
Thanks
