### ISSUE TITLE
Ability to bulk-clear checkbox state

### ISSUE THREAD

**Issue by dkonigsberg** [openscopeproject/InteractiveHtmlBom#293]
When I'm about to start a new build of a PCB that I've previously assembled using iBOM, I want to bulk-clear the state of all the sourced/placed/etc checkboxes so I'm starting from a clean slate.  Unless I'm missing something, I can see absolutely no way to actually do this from the UI. (And the way iBOM saves state in the browser's local storage makes this more frustrating, even if that's otherwise a good idea.)

The only approach I've found is to go into the browser's developer tools, and clear its local storage for the page. This works, but I also loose all of the other settings for the iBOM page in the process. Its also not very user-friendly to have to resort to this.

**Comment by qu1ck** [comment]
![image](https://user-images.githubusercontent.com/3622532/162487234-dbaaff26-108b-4d1c-8519-c46f8b92d5d2.png)

Double click on checkbox header toggles the whole column.

If you have suggestions on how to make this more noticeable I'm all ears but there is already a tooltip and it's explained in the wiki usage page.
