### ISSUE TITLE
The text variables in the date of the title block aren't expanded.

### ISSUE THREAD

**Issue by set-soft** [openscopeproject/InteractiveHtmlBom#295]
As you can see title, revision and company are expanded, but not date:

https://github.com/openscopeproject/InteractiveHtmlBom/blob/b07e364699346a7d9edaac25c2eaeab34eb22ba7/InteractiveHtmlBom/ecad/kicad.py#L678-L689

Some KiBot users put a variable there, so you get the date the file was processed (i.e. printed) and not a fixed date, or the date of the last commit, or ... anything they come with.

**Comment by set-soft** [comment]
I patched it like this: https://github.com/INTI-CMNB/InteractiveHtmlBom/commit/e14b02d12a2b0cb3cf25117c043ebcea4115bcf3

**Comment by qu1ck** [comment]
Can you open a pull request?

**Comment by set-soft** [comment]
> Can you open a pull request?

Done
