### ISSUE TITLE
Silkscreen font

### ISSUE THREAD

**Issue by f6fvy** [openscopeproject/InteractiveHtmlBom#3]
Great tool ! Thanks for the job !

It looks like the font displayed on the silkscreen image is a serif-font, while the font used in pcbnew (and on the actual PCB) is a sans-serif one.

A very minor inconvenience, but I wanted to let you know.

Running on Win7 / Firefox

**Comment by qu1ck** [comment]
That's weird. Can you post a screenshot? You can crop it to just show a piece of text.
Is it not monospace?
https://github.com/openscopeproject/InteractiveHtmlBom/blob/5ac0b1ed6685f24288abc22b81a70cf56ef5c23b/InteractiveHtmlBom/ibom.html#L510

Problem with pcbnew font is that it does not exist in ttf format, it's specially crafted for the purpose of being easily readable monospace font with low vector segment count.
I had to choose something that looks somewhat similar to it and has similar proportions. Monospace seemed like a good fit and had decent fallback on linux which doesn't have it.

**Comment by f6fvy** [comment]
![ibom](https://user-images.githubusercontent.com/12431844/43293006-5800c470-9138-11e8-8107-b78c40ee4d4c.png)

**Comment by qu1ck** [comment]
That looks like Courier New. I agree it's not the best.
If you change the line I linked from Monospace to Consolas, does it look better?

I will try to find a way to have better fallback.

**Comment by f6fvy** [comment]
Consolas is fine !

![ibom2](https://user-images.githubusercontent.com/12431844/43293254-8a69d504-9139-11e8-9c53-b2405e6acdec.png)

Thanks for your time !
