### ISSUE TITLE
incorrect drawing some rotated footprints

### ISSUE THREAD

**Issue by sborshch** [openscopeproject/InteractiveHtmlBom#305]
Here is how footprints looks in pcbnew:
![Screenshot from 2022-06-01 15-04-14](https://user-images.githubusercontent.com/14307080/171400290-241aefdf-339b-446c-9052-1e01886ef1ab.png)

Here is how they looks in html (pay attention to VD1, VD2, VD4, VD5, they are rotated copies of VD3):
![Screenshot from 2022-06-01 15-04-34](https://user-images.githubusercontent.com/14307080/171400707-8c8c3457-fbef-45af-a24e-000c0975620b.png)

File to reproduce:
[bom_bug.kicad_pcb.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/8813863/bom_bug.kicad_pcb.zip)

**Comment by qu1ck** [comment]
https://gitlab.com/kicad/code/kicad/-/issues/11732

Let's see what kicad devs response is, the rectangles in footprints are a weird outlier.

In the meantime you can change the rectangle to polygon to work around the issue.

**Comment by qu1ck** [comment]
Fixed, get latest from master.
