### ISSUE TITLE
Does not work in KiCAD 6.99

### ISSUE THREAD

**Issue by spflanze** [openscopeproject/InteractiveHtmlBom#311]
I attempted to run this plugin in KiCAD 6.99 in Pop!_OS 20.04 and got a long list of errors. The command sequence I used to install this plugin is:

`mkdir ~/.kicad/

mkdir ~/.kicad/scripting/
mkdir ~/.kicad/scripting/plugins
cd ~/.kicad/scripting/plugins
git clone https://github.com/openscopeproject/InteractiveHtmlBom.git`

Did I install the correct version of InteractiveHtmlBom?

The errors:
![InteractiveHtmlBom errors](https://user-images.githubusercontent.com/32908448/172457900-a7ee1767-4860-46ec-9e21-101cccf159fb.png)
.

**Comment by qu1ck** [comment]
Yes. Did you remove the plugin from plugin manager? You should.

**Comment by qu1ck** [comment]
If you still have issues lets continue in #282
