### ISSUE TITLE
Feature Request: Live Part Stock OR Run javascript inside column

### ISSUE THREAD

**Issue by waymond91** [openscopeproject/InteractiveHtmlBom#313]
Hello,
I'd love to be able to track the number of components in stock for a given project from within my html bom.
That way when maintaining projects and checking part statuses I don't have to look any farther than my git repo.
I'd love to contribute to the project or fork my feature if somebody can point me in the right direction within the project.

You can search for the stock quantity of a LCSC part using a simple GET request, for example:
`https://wwwapi.lcsc.com/v1/products/detail?product_code=C2565`

Another idea I had was to try and inject javascript into the Symbol Fields Table in KiCAD, but I couldn't get that to work:
![image](https://user-images.githubusercontent.com/3513523/175184599-82d3b881-1ae5-43e8-acdb-6b4322083344.png)
As you might be able to guess, I'm mostly a react developer...

Any ideas on how I might be able to get this working?

**Comment by qu1ck** [comment]
Read https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Customization

The bom event should give you a trigger to inject your API calling code. Or call it separately and only inject results on bom update.

**Comment by waymond91** [comment]
Very cool! 
I'm working on it right now, however I'm having trouble finding my plugin install location on MacOS. Can you point me in the right direction here?

I also tried just running the script as a standalone, but I get the following error:
```
/Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/platinfo.cpp(180): assert ""Assert failure"" failed in InitForCurrentPlatform(): failed to initialize wxPlatformInfo
/Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/platinfo.cpp(107): assert ""value"" failed in wxGetIndexFromEnumValue(): invalid enum value
/Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/common/platinfo.cpp(262): assert ""idx < (sizeof(wxPortIdNames)/sizeof(wxPortIdNames[0]))"" failed in GetPortIdName(): invalid port id
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

I install wxpython, but my environment could be poorly configured - I don't see a `requirement.txt`?

**Comment by qu1ck** [comment]
> I'm having trouble finding my plugin install location on MacOS. Can you point me in the right direction here?

Open `Configure paths` dialog from preferences menu of kicad and check the `KICAD6_3RD_PARTY` path.

There is no requirement.txt because the plugin doesnt need anything beyond what comes with kicad. To run it on non-linux system you have to run the python bundled with kicad, not the system one. Not sure where it is on mac.

**Comment by waymond91** [comment]
Thank you! Hopefully I can make something half-way decent!

**Comment by set-soft** [comment]
Hi @waymond91 !

Just my 2 cents: [KiCost](https://github.com/hildogjr/KiCost) is designed to find the costs and prices for a KiCad BoM, it currently supports the REST API for Digi-Key, Mouser, Newark/Farnell and TME. You need tokens for each distributor, they are free.

Both, KiCost and iBoM, are integrated by [KiBot](https://github.com/INTI-CMNB/KiBot). It runs on Linux and CI/CD environments, some users runs it on Windows (using WSL), for MacOS some adjust should be done, but I can assist you. Running KiBot on a GitHub action without any configuration you can get [this](https://inti-cmnb.github.io/kibot_variants_arduprog_site/Browse/t1-navigate.html).

Just in case you want to take a look at what is currently available.

**Comment by qu1ck** [comment]
Closing as non-actionable on my side. If you have more questions feel free to reopen.

If you do get your script working and are willing to share it I can add it to examples on the wiki page.
