### ISSUE TITLE
Sort order on custom fields out of order

### ISSUE THREAD

**Issue by jwilo** [openscopeproject/InteractiveHtmlBom#315]
I'm not entirely sure if this is a bug, or me simply missing the point!

I've added a couple of custom fields, exported from KiCAD V6's netlist - and whilst they show just fine in the HTML output, clicking the column header to sort by Ascending or Descending does not seem to actually sort the data.

For example, I have a custom field "Place Sequence" used to sort the BOM in order of component placement, where a defined pattern of placement is desired. 

![Sort order](https://user-images.githubusercontent.com/89950407/176710376-bf79a059-87e6-46a2-b186-4809b958aee3.PNG)

If I sorted ascending, I get 9, 10, 130 165 and on....

Descending gives 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 9, 89, 88 (but note, the BOM contains entries 250+, so it's starting in the wrong place too).

KiCAD 6.0.5, Windows 10, plug in installed today (30/06/22).

**Comment by jwilo** [comment]
Adding to this, columns containing alphabetical characters only appear to sort correctly, as does the numerical quantity column generated by KiCAD.

**Comment by qu1ck** [comment]
It works as expected, the data is compared as strings, in lexicographical order.
You should pad your single and double digit numbers with zeroes and then it will work as you want, i.e. 001 002 003 etc.

**Comment by jwilo** [comment]
Great, thanks. This worked as you say and allowed me to sort by desired build order.

I must say, this tool is absolutely fantastic. I assembled 1x complex SMD board with ~450 parts, that I built 2x a year ago or so, and brought the assembly time down from 5 hours to 2 hours using this, it's fantastic. Your decision to open-source this is greatly appreciated, and will lead me to make another donation to KiCAD given I see you don't take donations directly. 

However, I do think with this sorting - it would make more sense from a user point of view if padding was not required - simply because whilst sorting in lexicographical order is technically expected behaviour, it is not typically expected behaviour from an end user point of view - especially when there is a quantity column next to it, which you can sort in numerical order without padding zeros.

**Comment by qu1ck** [comment]
Glad you like this tool.

I agree that this can be unexpected for end user. The difference between quantity and custom fields is quantity is known to be an integer and can be treated as such while custom fields can be anything. And more often than not they are not plain numbers.

Still, I could check if the whole column can be parsed as integers and then convert them, it's a nice addition.

**Comment by qu1ck** [comment]
Fixed in 2f38736, you shouldn't have to pad with zeros anymore.

If you want to get this fix before next version is released make sure to download latest from github and remove the plugin from the plugin manager, they can't coexist.
