### ISSUE TITLE
Pad shape offset

### ISSUE THREAD

**Issue by atwc** [openscopeproject/InteractiveHtmlBom#32]
Great tool!, I find a small bug on pad visualisation:

Apparently the viewer don't take into account the pads shape offset.

Pads on the viewer
![image](https://user-images.githubusercontent.com/1255625/45031312-c42cad00-b04e-11e8-8ce3-39cb76c1e52b.png)
Pad on Kicad
![image](https://user-images.githubusercontent.com/1255625/45031435-1c63af00-b04f-11e8-8613-5aaf524334da.png)

Pad Parameter
![image](https://user-images.githubusercontent.com/1255625/45031463-30a7ac00-b04f-11e8-8cdf-74cabe57574c.png)

**Comment by qu1ck** [comment]
Thanks for the report.
