### ISSUE TITLE
Allow rotating front/back separately/inversely

### ISSUE THREAD

**Issue by dotsam** [openscopeproject/InteractiveHtmlBom#328]
When using a rotating board holder (like the [SN-390](https://www.prokits.com.tw/Product/SN-390) and clones), it would be nice to see the front and the back layers in the same orientation that the board is when rotating the holder.

Not sure if this should be implemented as two rotation sliders, a dropdown to select front/back rotation, or just a checkbox to cause the layers to rotate inversely. I'm leaning towards the checkbox out of simplicity, and not being able to think of any other use-cases for completely separate and arbitrary rotation.

A quick look at the code seems to indicate that this shouldn't be too hard to do, so I might take a run at a PR in the next week or so if you think this is a good idea.

**Comment by qu1ck** [comment]
For that effect you want to rotate with 180º phase shift, not inversely.

Checkbox sounds fine. Just make sure to update highlight logic and click detection.
