### ISSUE TITLE
Grouped items, not being grouped.

### ISSUE THREAD

**Issue by ScaredyCat** [openscopeproject/InteractiveHtmlBom#345]
Running version 2.5

When generating the BOM I'm opting to group by Value,footprint and LCSC (LCSC part code) but some of the items are not being grouped together:

Selection/grouping:

![bom-issue1](https://user-images.githubusercontent.com/168872/211319715-3010db80-f6cc-4537-9da5-2c0cf635fab6.png)

Items not being grouped:

![domissue2](https://user-images.githubusercontent.com/168872/211319862-df78fbe2-25ff-45ee-ae1f-eaa62e98a617.png)

It appears that the reference is playing a part in the grouping, ignoring all other, imho more relevant, selections.

**Comment by qu1ck** [comment]
Ibom tries to be smart about values for them to be correctly sortable and recognize both SI prefixes and units. When units are not indicated it tries to infer them based on reference. So it will recognize that 10k means 10 kiloohms if the component is "Rxxx" where x are digits but it will not recognize a weird reference as a resistor and will not group "10k" string to 10000 ohm resistors.

So you can either specify value as 10kohm, 10kΩ, 10kR or not use weird references but I don't see how to fix this edge case without causing other issues for more common cases.

**Comment by ScaredyCat** [comment]
If I disable 'Value' as a group by and leave footprint and the part code, then grouping is done as desired. 

For items without a part code, grouping by footprint works for this board but ideally you'd be able to group by, for example, part number and if that's empty fall back to value. i.e. prioritise the grouping, in a similar way to the display order perhaps ?

**Comment by qu1ck** [comment]
That is another layer of grouping complexity that I think is over the top. 

And the core issue of value parsing will still be there and mess with sorting.
