### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by rozrabiak** [openscopeproject/InteractiveHtmlBom#347]
Kicad 6.0.10

![Zrzut ekranu 2023-01-10 220604](https://user-images.githubusercontent.com/73905882/211662527-03308b16-138b-4089-bf1b-2ec4b644a1ae.jpg)

**Comment by qu1ck** [comment]
It looks like you are trying to install from file but you downloaded the wrong file.

I recommend you install directly from plugin manager by clicking install on the plugin and then apply changes.
If you don't have internet connection on the pc where you want to install then you can install from file but you have to grab the correct archive. On the release page there are 2 downloads, zip file that is suitable to install in plugin manager ends with `_pcm.zip`.

Direct link to current latest version is https://github.com/openscopeproject/InteractiveHtmlBom/releases/download/v2.5.0/InteractiveHtmlBom_v2.5.0_pcm.zip
