### ISSUE TITLE
First pin highlight inconsisten (e.g. too **fat**)

### ISSUE THREAD

**Issue by eflukx** [openscopeproject/InteractiveHtmlBom#349]
When selecting "Highlight first pin", the markings can become way too **fat** on several (most) components. Some components are properly highlighted, but most are not. Also when there are for example a couple of the _same_ components are in a row, some may have the '_fat_' highlight, while others are correctly highlighted.

See example screenshot:
- Q8 is ok, Q7 not
- R31 is ok, R29 not
- etc.

![image](https://user-images.githubusercontent.com/996191/212727748-93e34499-1147-416f-b620-55a52a1c316d.png)

**Comment by qu1ck** [comment]
What's your kicad version and plugin version?

Can you share the design or a minimal/stripped version that shows the issue?

**Comment by qu1ck** [comment]
I was able to reproduce it, fix committed.

**Comment by eflukx** [comment]
That's mighty quick indeed my friend! 😉 

Sorry I forgot the version nrs. indeed, for the record here they are:

 - Kicad 6.0.10 (release) on Windows 
 - Plugin version v2.5.0 (installed from the KiCad repo)
