### ISSUE TITLE
How to use in allegro？

### ISSUE THREAD

**Issue by strangerby** [openscopeproject/InteractiveHtmlBom#354]
I clicked the run .bat and entered the allegro file path into a carriage return, and the program reported an error.

fatal: not a git repository (or any of the parent directories): .git
Git version check failed: Command '['git', 'describe', '--tags', '--abbrev=4', '--dirty=-*']' returned non-zero exit status 128.
Loading C:\Cadence\SPB_17.4\share\pcb\toolbox\getting_started\mfgdoc\demo.brd
Traceback (most recent call last):
  File "C:\Users\yzy\Downloads\InteractiveHtmlBom\InteractiveHtmlBom\generate_interactive_bom.py", line 79, in <module>
    main()
  File "C:\Users\yzy\Downloads\InteractiveHtmlBom\InteractiveHtmlBom\generate_interactive_bom.py", line 66, in main
    ibom.run_with_dialog(parser, config, logger)
  File "C:\Users\yzy\Downloads\InteractiveHtmlBom\InteractiveHtmlBom\core\ibom.py", line 326, in run_with_dialog
    dlg = SettingsDialog(extra_data_func=parser.parse_extra_data,
                                         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parse_extra_data'
-------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------

ECHO is off.

**Comment by qu1ck** [comment]
Read [wiki](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Usage#standalone-script) there is a note for allegro users.

You need to export json before feeding it to ibom.
