### ISSUE TITLE
wxwidgets debug alert

### ISSUE THREAD

**Issue by Hcreak** [openscopeproject/InteractiveHtmlBom#355]
- python:  Python 3.9.13
- wxpython:  4.2.0

![image](https://user-images.githubusercontent.com/15710701/218776260-6c12407a-338e-4b0c-8196-b9feb766fe32.png)
![image](https://user-images.githubusercontent.com/15710701/218776379-4494b8bd-5b7f-417a-96fb-639ede005893.png)
![image](https://user-images.githubusercontent.com/15710701/218776453-d01b61ff-94ab-413d-a660-ffc791ed9000.png)

**Comment by qu1ck** [comment]
Is this happening on latest from master?

**Comment by Hcreak** [comment]
> Is this happening on latest from master?

latest [Releases v2.5.0](https://github.com/openscopeproject/InteractiveHtmlBom/releases/tag/v2.5.0)

**Comment by qu1ck** [comment]
Download latest from github master branch, not release.

**Comment by Hcreak** [comment]
> Download latest from github master branch, not release.

Thx. this is true.
With the [Releases v2.5.0](https://github.com/openscopeproject/InteractiveHtmlBom/releases/tag/v2.5.0), I suggest annotating or deleting it.  so as not to cause the same error.
