### ISSUE TITLE
Oversized Footprint Outline

### ISSUE THREAD

**Issue by myamigo** [openscopeproject/InteractiveHtmlBom#357]
I have a small FPGA in my design that has a properly defined footprint but the red outline in the ibom.html output is extending way past the courtyard. Part is U18 below...

![image](https://user-images.githubusercontent.com/17319745/219405051-9e69e442-5267-44f7-ab5e-765c68857d00.png)

After closer examination it seems the plugin is using the dimension line objects on the User.Comments layer to determine the extents for the part. I added a yellow box around the dimension lines after doing a screen grab from the Footprint Editor...
![image](https://user-images.githubusercontent.com/17319745/219407254-eed8a8f4-0f61-41b5-bbb9-35d2163ad9be.png)

The red and yellow frames are perfectly correlated. If the courtyard is defined then that might be the best object to use to determine the red box dimensions. If there is no courtyard then use the Fab layer objects and barring that perhaps use the silk and pads. In any case I wouldn't use the User.* layer objects for this purpose.

Great plugin! 👍

**Comment by qu1ck** [comment]
Ibom doesn't look at any specific layer contents, it uses bounding box logic of kicad. If kicad thinks those drawings are within the box, ibom will draw it truthfully.

I agree that dimension objects should not be included when text is not included. But that should be fixed on KiCad side.

**Comment by myamigo** [comment]
I see. KiCad doesn't also consider the associated text so there's some inconsistency there for sure. It's a minor thing so moving on.

**Comment by qu1ck** [comment]
Fixed in kicad with https://gitlab.com/kicad/code/kicad/-/merge_requests/1522. This should be in 7.0.2
