### ISSUE TITLE
Error when running on a PCB with a bitmap image

### ISSUE THREAD

**Issue by dkonigsberg** [openscopeproject/InteractiveHtmlBom#359]
When a PCB layout contains a bitmap image (KiCad v7's new "Add bitmap image" option), the HTML BOM generation process fails with an error.  I've attached a screenshot of the stack trace dialog that pops up when doing this.

![image](https://user-images.githubusercontent.com/1144556/220703838-c5f1a815-bf7d-4e5e-9939-84cbbc2cc515.png)

For now, the workaround is to delete any bitmaps from the PCB prior to generating the HTML BOM.
A better solution would simply be if the HTML BOM plugin could ignore these elements when doing its thing, as they're primarily for decoration/reference when doing layout.

(This is with Interactive HTML BOM v2.5.0 and KiCad v7.0.0.)

**Comment by bwack** [comment]
Same experience here.
v2.5.0, kicad v7.0.0, ubuntu 20

**Comment by qu1ck** [comment]
It's a KiCad bug. See https://gitlab.com/kicad/code/kicad/-/merge_requests/1525
Workaround is possible but not sure it's worth it if 7.0.1 will have the fix.

**Comment by qu1ck** [comment]
7.0.1 is out with the fix.
