### ISSUE TITLE
Ability to uncheck all checkboxes

### ISSUE THREAD

**Issue by tehKaiN** [openscopeproject/InteractiveHtmlBom#36]
Suppose I'm assembling two boards and have "placed" checkbox. After I'm finished with one board I'd have to remove checkbox column and add it again so that it gets reset. But there could be a button for clearing all checkboxes so that I'm ready for assembly of 2nd board. I could also add 2nd column, but suppose I'm assembling 10 small boards - I don't like the idea of having 10 columns for that ;)

**Comment by qu1ck** [comment]
I think I will make the checkbox column header clickable with a hint that will explain that it will set/unset checkbox for all rows.

Right now even removing and re-adding a checkbox will not clear it.
