### ISSUE TITLE
Add support for Kicad's native DNP field

### ISSUE THREAD

**Issue by Shackmeister** [openscopeproject/InteractiveHtmlBom#361]
In Kicad 7 there is now a native/dedicated option for DNP.
Ultimately this could replace the whole dnp selection section.

Thank you for a great plugin!

**Comment by iyzpx** [comment]
Created a pull request: #370

Currently it's just ignoring/hiding the components in the bom flagged with dnp. IMO this might work now, but I would imagine it is better to mark the components as the kicad schematic does:

![image](https://user-images.githubusercontent.com/103630942/229761159-6c2e8f0e-da96-4e27-b3ef-5c805250b896.png)

**Comment by qu1ck** [comment]
There is an option to draw dnp components in outline mode. Cross doesn't work as it does in schematic because on pcb components can overlap.

**Comment by andrewgreenberg** [comment]
Just bumping this; it would be GREAT to support KiCAD 7 DNP!

**Comment by qu1ck** [comment]
Native dnp field is now supported, will be in next version. To use it select `kicad_dnp` as DNP in fields tab in config

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3622532/8176fea6-7c86-4cb1-b89a-5740c9e7888f)
