### ISSUE TITLE
(Un)selectable text

### ISSUE THREAD

**Issue by itskando** [openscopeproject/InteractiveHtmlBom#363]
Is there a means to make the text selectable, for copy/pasting purposes?

**Comment by qu1ck** [comment]
Which text?

**Comment by itskando** [comment]
Anything in any of the columns.


![image](https://user-images.githubusercontent.com/15063663/226496937-82cb9ae7-7aa9-4def-8598-08cb8dc8c780.png)

**Comment by qu1ck** [comment]
There is a copy button just for that 
![image](https://user-images.githubusercontent.com/3622532/226513004-2400275a-5bfb-4168-8971-ad772e6751d2.png)
