### ISSUE TITLE
Eagle: the script doesn't generate output if the outline is drawn as a component

### ISSUE THREAD

**Issue by depalamarchuk** [openscopeproject/InteractiveHtmlBom#366]
The script doesn't see Dimension layer in library. It can be easily fixed by copying the outline from library to board though. The attachment has a minimum (not) working example.
[iBOM_dimension_test.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/11102058/iBOM_dimension_test.zip)

**Comment by qu1ck** [comment]
Thanks for bug report with test project.

@Funkenjaeger wanna take a look?

**Comment by Funkenjaeger** [comment]
Will do.

**Comment by Funkenjaeger** [comment]
Fix pushed, PR #367.  I second what @qu1ck said above - an [SSCCE ](http://sscce.org/) is always appreciated, thank you!
<img width="955" alt="image" src="https://user-images.githubusercontent.com/24237058/228691992-0535a622-2fde-49c4-a050-ec587b02659b.png">

**Comment by depalamarchuk** [comment]
Hello,

Thank you for fixing it fast. However, with some shapes it still doesn't work. Probably it cannot process arcs connected to arcs. Sometimes it does work, so I cannot reproduce the bug consistently. Deleting stuff at 103 Test layer (not present here) also helped. I'm not sure what is going on here. But copying it to board still works as a temporary fix. I'm attaching another example board.

[iBOM_dimension_test2.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/11108584/iBOM_dimension_test2.zip)

**Comment by Funkenjaeger** [comment]
Sorry about that @depalamarchuk, I overlooked a one-line change in my previous fix.  I pushed a fix in my fork (97cae23) - to perhaps learn a lesson from my earlier haste, why don't you give it a try before I submit another PR :)

**Comment by depalamarchuk** [comment]
@Funkenjaeger Thank you for a fix. Now it works with complex shapes.

**Comment by qu1ck** [comment]
@Funkenjaeger please open a PR with that commit.
