### ISSUE TITLE
Parts included in bill of materials and exluded from board are not shown in the interactive bom

### ISSUE THREAD

**Issue by bwack** [openscopeproject/InteractiveHtmlBom#371]
Lately I've figured out it is possible to add (digikey etc) order numbers to the ibom by using the symbols field table in the schematic editor, and when creating the ibom, I select that field in the InteractiveHtmlBom form, Fields tab:

![Screenshot_2023-04-08_01-00-21](https://user-images.githubusercontent.com/11380333/230690193-63385618-33d6-4020-834b-be0d7a4ed74c.png)

The result is great:
![Screenshot_2023-04-08_01-03-06](https://user-images.githubusercontent.com/11380333/230690312-3bf87e4b-e691-4ff3-85e8-c97fbe4cb264.png)

Though, sometimes in large projects like mine, you have multiple orders per part. Say you want DIP sockets with your 74LS14 ICs, or you have this large glass fuse, but you also need the fuse holder. In my case that is the glass fuse + two fuse clips. My solution to this was to add symbols in the schematics indicating the fuse clips, and in their properites set them to be in the bom, but not on the board, only the fuse is on the board and linked to an actual footprint. So I wonder, why they don't show up in the ibom ?
Is it because the interactivehtmlbom script only looks in the pcbnew file, and not in the schematics file ? 

Somehow quirky I could add dummy footprints that that links with the schematics, and are made of graphics on the user drawing layer only .. I suppose in that way I might get it to work, but that defeats the purpose of having them "exluded from board"

**Comment by qu1ck** [comment]
Yes, it's because ibom only uses things that are on the board.

Ibom is not intended to be project level BOM. Your issue is no different from trying to include wiring harness/terminals or fasteners or other auxiliary things into the BOM: if it doesn't have a footprint then it's not in ibom.

Intended solution for this is to export your bom to another tool that manages complex project level bom. There is a copy to buffer button at top right corner of the table and export to csv/txt functions in one of the menus.

**Comment by bwack** [comment]
OK. Thanks !

**Comment by set-soft** [comment]
> Though, sometimes in large projects like mine, you have multiple orders per part. Say you want DIP sockets with your 74LS14 ICs, or you have this large glass fuse, but you also need the fuse holder.

In my projects I add a symbol for each thing. I.e. a LED with a LED pipe, I add an extra symbol for the LED pipe, not necessarily with a corresponding footprint. 
KiCost approach is different, read the docs, it supports multiple parts in on symbol. KiBot supports the KiCost mechanism. 
IMHO iBoM shouldn't be used as a BoM generator, but an assembly helper.

**Comment by bwack** [comment]
I don't agree by the intention, but I respect the decision by the author. If it is not the intention to be the main bom I'll go with csv files instead when ordering. I'll look into KiCost, thanks.
