### ISSUE TITLE
Sometimes Tracks are not showing up

### ISSUE THREAD

**Issue by tormyvancool** [openscopeproject/InteractiveHtmlBom#372]
KiCAD 7.0.1
Your Script version: 2.6.0
If you see the settings, they are not checked. While in several other projects: they are.

Is there anything wrong ? Or I miss?

![image](https://user-images.githubusercontent.com/32305535/231708394-ffe15ae9-ea3e-46b8-92d4-aecb94c16f08.png)
But there are into the project. And Gerbers files are correct.

![image](https://user-images.githubusercontent.com/32305535/231708760-188049df-a9d2-4b90-b82a-409eec5750ee.png)

![image](https://user-images.githubusercontent.com/32305535/231709028-16e8bbcc-c727-4d8d-a635-494709b98c2c.png)
![image](https://user-images.githubusercontent.com/32305535/231709081-dc357026-97f0-4e82-b9dc-557e30ea7641.png)
![image](https://user-images.githubusercontent.com/32305535/231709140-8fe8fdb1-840d-424e-93bb-fc3af6cce612.png)

**Comment by qu1ck** [comment]
Settings in your html page are remembered in browser. If you at some point generated ibom without tracks/zones then corresponding setting will be set to disabled. If you later generate it again but include tracks/zones then you have to manually reenable tracks/zones in html to view them.

**Comment by tormyvancool** [comment]
> Have you tried click on Tracks? ![image](https://user-images.githubusercontent.com/20681096/231733570-f445ae63-dcd2-4724-8ce3-97d98e9c4119.png)

Yes of course: then they appear. but the goal is to export in a way that **automatically** I find the checkboxes full checked. And this doesn't occur any longer.

**Comment by tormyvancool** [comment]
> 

It's what I did. I enabled them and regenerated but I go them back unchecked. Then I came here to ask ...
