### ISSUE TITLE
Filter crashes when using kicad_pcb extra data field for part number

### ISSUE THREAD

**Issue by hardwaremaker** [openscopeproject/InteractiveHtmlBom#376]
When trying to filter the BOM, the filter raises an error and shows nothing in the list. It seems like the INX-Part number is causing the behaviour. Works when not adding the extra field.
Version is 2.6

![Bildschirmfoto vom 2023-04-17 21-42-13](https://user-images.githubusercontent.com/59623495/232594229-51ef9b5a-0ba4-4247-9084-68b6c9f022d2.png)

**Comment by qu1ck** [comment]
Thanks. I pushed a fix, you'll have to install manually from master (see wiki for instructions) if you don't want to wait until next release.
