### ISSUE TITLE
'EDA_RECT' has no attribute 'GetTop'

### ISSUE THREAD

**Issue by anderwm** [openscopeproject/InteractiveHtmlBom#38]
Sorry, just saw only supports Kicad 5!!!

Hello, I was giving this a try on some boards made in Kicad4
Version: 4.0.7-e2-6376~61~ubuntu18.04.1, release build

I got the following:

> ../src/common/object.cpp(251): assert "classTable->Get(m_className) == NULL" failed in Register(): Class "wxSimpleHtmlListBox" already in RTTI table - have you used IMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
Loading ...filename
09:05:57: Debug: Skipping general section token 'links' 
09:05:57: Debug: Skipping general section token 'area' 
09:05:57: Debug: Skipping general section token 'drawings' 
09:05:57: Debug: Skipping general section token 'tracks' 
09:05:57: Debug: Skipping general section token 'zones' 
09:05:57: Debug: Skipping general section token 'symbol' 
Traceback (most recent call last):
  File "InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py", line 509, in <module>
    main(pcbnew.LoadBoard(os.path.abspath(args.file)), not args.nobrowser)
  File "InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py", line 441, in main
    "miny": bbox.GetTop() * 1e-6,
  File "/usr/lib/python2.7/dist-packages/pcbnew.py", line 1415, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, EDA_RECT, name)
  File "/usr/lib/python2.7/dist-packages/pcbnew.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'EDA_RECT' object has no attribute 'GetTop'

The first bit is repeated many times, but I doubt that is where the error is.
Does InteractiveHtmlBom only work in Kicad5? Or is there something else obvious I am missing?

**Comment by qu1ck** [comment]
While I test mostly with KiCad5 I try to keep InteractiveHtmlBom mostly compatible with KiCad4 too. This is a regression that should be fixed.

**Comment by anderwm** [comment]
Ok, I opened the file in pcbnew of Kicad5 and resaved it and then it worked. This is a really useful tool, thanks. If I can help you track down the error from my version of Kicad4 let me know.
