### ISSUE TITLE
KiCAD 7.x DNP doens't work at all for me

### ISSUE THREAD

**Issue by slagdang** [openscopeproject/InteractiveHtmlBom#380]
Using KiCAD 7.0.2. In installed this plugin using the KiCAD plug in manager. The version of this plugin is 2.6.0. It says so in the window that comes up.

I saved my PCB before running this plugin.

I select to display and group by a field called DNP and Voltage (for capacitors) as well as the default.

I have two items in my schematic (R22 and C23) which are marked DNP. These do not come up DNP in the interactive BOM.

If I export to other kinds of BOMs using the BOM exporter in eeschema they come up as DNP.

I looked through the documentation for this plugin to see if there are some tricks to getting this to work and I can't find anything.

As far as I know (from writing my own BOM exporter nowhere near as good as yours) that the DNP attribute in KiCAD 7 has no value. It's not even a field, only a property. See snippet from xml version of my schematic that KiCAD exported:

    <comp ref="C22">
      <value>10u</value>
      <footprint>Capacitor_SMD:C_0805_2012Metric</footprint>
      <fields>
        <field name="Voltage">25V</field>
      </fields>
      <libsource lib="Device" part="C" description="Unpolarized capacitor"/>
      <property name="Voltage" value="25V"/>
      <property name="Sheetname" value=""/>
      <property name="Sheetfile" value="driver.kicad_sch"/>
      <property name="ki_description" value="Unpolarized capacitor"/>
      <property name="ki_keywords" value="cap capacitor"/>
      <sheetpath names="/" tstamps="/"/>
      <tstamps>45757b1b-662b-49d6-ab91-43834de6218d</tstamps>
    </comp>
    <comp ref="C23">
      <value>10u</value>
      <footprint>Capacitor_SMD:C_0805_2012Metric</footprint>
      <fields>
        <field name="Voltage">25V</field>
      </fields>
      <libsource lib="Device" part="C" description="Unpolarized capacitor"/>
      <property name="Voltage" value="25V"/>
      <property name="Sheetname" value=""/>
      <property name="Sheetfile" value="driver.kicad_sch"/>
      <property name="dnp"/>
      <property name="ki_description" value="Unpolarized capacitor"/>
      <property name="ki_keywords" value="cap capacitor"/>
      <sheetpath names="/" tstamps="/"/>
      <tstamps>d0c45403-0f30-4dfe-bbe5-ef15ad471155</tstamps>
    </comp>

My BOM emitter outputs HTML that produces these two lines:

C22 | 1 | 10u | Device:C | Capacitor_SMD:C_0805_2012Metric | Unpolarized capacitor |   | 25V
C23 | 1 | 10u | Device:C | Capacitor_SMD:C_0805_2012Metric | Unpolarized capacitor |   | DNP 25V

I merge the voltage with DNP for a single column in my python code. And you can see the BOM python emitter also didn't group them as it would have if they had the same DNP attribute.

But in your tool it fails to see DNP at all even though it does show it as a field to group by and show (and I check the box for both of them). It's just the DNP column is completely blank and the grouping works as if it were.

Am I doing something wrong? Would you like me to attach a project which shows this issue?

**Comment by slagdang** [comment]
I looked in pcbnew at C23 and "exclude from BOM" is not checked. I wouldn't expect it to, as DNP is not the same as exclude from BOM. But I thought I would mention this as maybe they are supposed to be the same and aren't in my project somehow.

**Comment by qu1ck** [comment]
> I select to display and group by a field called DNP and Voltage (for capacitors) as well as the default.

Just to clarify, you mean in the fields tab of the plugin you checked "show" and "group" next to DNP? 

If you did that, it has nothing to do with the DNP flag that you set in symbols. In fact ibom currently does not support the new DNP flag in symbol properties that kicad v7 introduced.
The reason you see DNP in the fields list in ibom is because you have some component that has a custom field with name DNP.
If you want to see correct DNP value in ibom then you have to set that custom field value accordingly, then update pcb from schematic to have those custom fields propagated to pcb.

**Comment by qu1ck** [comment]
> "exclude from BOM"

That one is what replaced "virtual" components in kicad pre v6. There is "blacklist virtual components" setting in ibom which will completely remove such components from ibom.

**Comment by slagdang** [comment]
Okay. Thank you. The comment that says DNP doesn't work explains it all for me. I'm bummed, but it explains it all.

I guess just mark me down as one of the people looking forward to DNP support. I can even try to make a patch if you would like. Or just wait.

If you have no need for an issue which tracks future DNP support then this issue is done, no reason to keep it open.

Thank you for your time.

**Comment by slagdang** [comment]
And thank you for the indication that the "DNP" is there because I put it on some component. I used to do that back in KiCAD 5 and 6. And I must have missed removing one. I'll find it and remove it.

**Comment by qu1ck** [comment]
#361 exists for native dnp support. But it will not do what you expect it to do, it will allow DNP marked components to not be included in bom at all. It will not add a column to the table.

Only way to add a column is to have an custom field that you add in fields tab.

**Comment by slagdang** [comment]
Thank you very much. I really just need two things:

The outlines you mention to work for KiCAD DNP items.
Grouping to separate out the DNP items (and mark them like you say, a column) so that I can mark the items as placed when I begin the process so I don't place them later.

Anyway, I am just expression what I would use it for. I fully understand that the features you put in are your own decisions. I'm not trying to be demanding.

I'm going to use the existing version of the tool again today! It's such a great tool.

**Comment by qu1ck** [comment]
Glad you like the tool. I will definitely add native dnp support, can't promise that it will be soon though.
