### ISSUE TITLE
DNP outlined components are marked green => placed

### ISSUE THREAD

**Issue by nopeppermint** [openscopeproject/InteractiveHtmlBom#381]
I have an issue with the DNP outlined feature:

I assembled before some components, therefore they were once marked as assembled.
Now I decided to not assemble them and but the DNP field in Kicad.

Now it looks like this:

![image](https://user-images.githubusercontent.com/3403218/233304686-a73234ab-2007-41d1-9169-58d81c086c72.png)

Red => currently selected component => all good
Green => placed components, but they also have the DNP flag and are therefore not with a solid grey pad => bug 1
Some of the components => round testpoint in the bottom right corner are excluded from the ibom but still have the "placed" green color..

**Comment by nopeppermint** [comment]
I would expect only components to be marked green when:

A = they are placed
B = they are not excluded via DNP
C = they are not excluded via "component blacklist" on creation

so => green = A & B & C

;-)

**Comment by nopeppermint** [comment]
btw. this happens independent if I delete the old ibom file before creating or not, seem to be stored somewhere else in a cache..

**Comment by nopeppermint** [comment]
the only way to fix it manually is to:
- toggle those two flags in the Kicad PCB 
![image](https://user-images.githubusercontent.com/3403218/233306693-3afffcea-5a8d-45c3-9bf1-981c4c51be96.png)
- generate ibom
- mark all components as not placed
- toggle back the two flags in Kicad PCB
- regenerate ibom

**Comment by nopeppermint** [comment]
and for the TP* the "component blacklist" has to be deleted, generate ibom, toggle the placed flag, but pack the component blacklist, regenerate ibom

![image](https://user-images.githubusercontent.com/3403218/233308504-28e8faa0-c8a2-4ea6-b112-083022cf7f1a.png)


BTW. I use InteractiveBOM v2.6.0 from the kicad package manager

**Comment by qu1ck** [comment]
Checkbox state and other settings are stored in browser local storage and it is tied to board name and revision.

It is assumed that if you change the board significantly you would bump revision as well, that way settings will effectively reset. But there probably should be a manual reset button.

As a workaround you can reset settings manually by opening browser dev tools and removing entries from local storage 

![image](https://user-images.githubusercontent.com/3622532/233488930-a68b4780-37e1-40f6-a9a7-b66efe13990c.png)

or by invoking personal data removal tool in your browser (ctrl-shift-del in chrome), but this will delete a lot of stuff.

**Comment by dresco** [comment]
> Checkbox state and other settings are stored in browser local storage and it is tied to board name and revision.

May I check, where is the revision taken from - the schematic page settings? Thanks...

**Comment by qu1ck** [comment]
No, board page settings. Ibom uses board data for everything, only exception is extra fields that you can optionally source from netlist file or eeschema generated xml.

**Comment by dresco** [comment]
> No, board page settings. Ibom uses board data for everything, only exception is extra fields that you can optionally source from netlist file or eeschema generated xml.

Ah yes, got it. Thank you!

**Comment by qu1ck** [comment]
Ok, there is now a reset button allowing you to start from a clean slate.

**Comment by nopeppermint** [comment]
thanks @qu1ck  would be nice if you could also create a new Kicad Plugin release version
