### ISSUE TITLE
Board variant section not accessible in configuration

### ISSUE THREAD

**Issue by ajohn77** [openscopeproject/InteractiveHtmlBom#382]
iBOM configuration window doesn't show properly the whole "board variant" section in Fields tab. This section seems be cut - the whole window is probably too small and unfortunately not resizable.
![iBOM_board_variant_missing](https://user-images.githubusercontent.com/132054827/235106345-c9321147-b1c9-4795-b948-154b8c0a6c11.png)

iBOM v.2.6.0 Kubuntu 22.04 Python 3.10.6

**Comment by qu1ck** [comment]
Should be fixed now. You'll have to manually install latest from master if you want to get the fix before next release.

**Comment by ajohn77** [comment]
excellent, thanks.
