### ISSUE TITLE
Merging various footprints

### ISSUE THREAD

**Issue by mondalaci** [openscopeproject/InteractiveHtmlBom#385]
Due to inconsistent space constraints, many of our parts have multiple footprints, such as MyPart and MyPart_chamfered. In the BOM list, MyPart_chamfered and related parts should all translate to MyPart. The feature would greatly reduce the number of BOM rows and make this tool much more useful.

Does such a feature exist?

The most flexible implementation of this feature I can think of is an optionally implementable callback function that iterates all parts, and the function returns the original part or a modified version of it.

**Comment by qu1ck** [comment]
Solution to this is to disable grouping by footprint and instead group by some other field that is actually unique for part, like MPN for example.

**Comment by qu1ck** [comment]
> Assuming that updating a symbol based on schematic might delete an existing module property, I added a "Package" symbol property and then used the "Tools > Update PCB from Schematic..." menu item to copy the symbol property as a module property.

Yes, that's the way to do it.

> ...I can see that the "Footprint" property is present...

Which is it? "Package" or "footprint"?

> it's not visible in the "Footprint Properties" dialog of the part.

Custom properties are not editable in pcb, they just get imported from schematic.

> my script does not duplicate the related board.

But it sounds like it duplicates footprints and that will copy properties too so what you see is normal. Also don't you want the property to be duplicated? Otherwise grouping will not work. 

> Do you mean that there are select property names that are considered unique?

There are no special property names. I just suggested that in your case whatever you consider "unique" as in "correctly identifying the physical part" will do. Even for the same board different grouping options may be useful for different purpose: 

For example for procuring parts it makes sense to have both upright mounted to220 mosfet and the bent down horizontally one to be grouped together. But for assembly machine (or hand assembly) they should probably not be grouped.

**Comment by mondalaci** [comment]
> > Assuming that updating a symbol based on schematic might delete an existing module property, I added a "Package" symbol property and then used the "Tools > Update PCB from Schematic..." menu item to copy the symbol property as a module property.
> 
> Yes, that's the way to do it.
> 
> > ...I can see that the "Footprint" property is present...
> 
> Which is it? "Package" or "footprint"?

Sorry, I meant "Package".

> > my script does not duplicate the related board.
> 
> But it sounds like it duplicates footprints and that will copy properties too so what you see is normal. Also don't you want the property to be duplicated? Otherwise grouping will not work.

[The related code of my pcbmerge fork](https://github.com/mondalaci/KiCad_PCBmerge/blob/77c6b7fcb6510ced978c20f78431e4cdb83f32c6/pcbmerge.py#L114-L128) shouldn't duplicate parts, but maybe it somehow does. I combine 5 boards. 4 boards have J1 components on them of which 2 are USB-C connectors and 2 are FFC connectors. For some reason, the same "Package" value gets assigned to all 4 of them instead of a single part.

**Comment by qu1ck** [comment]
Ah, I see, I thought your script is sort of panelizer so it copied the same board. Yeah, if you merge different boards you don't want properties to duplicate.

> For some reason, the same "Package" value gets assigned to all 4 of them instead of a single part.

Do you see that property only in ibom or in resulting kicad_pcb file too? If it's only in ibom, does it show the value for each part in ungrouped mode too?

If it's in pcb file then this is a kicad bug. Would be interesting to boil it down to minimal example with 2 boards of just 1 footprint each and this line of code:
```py
        # Append new board file with modified net names
        plugin = IO_MGR.PluginFind(IO_MGR.KICAD_SEXP)
        plugin.Load(fname, pcb)
```
screwing it up.

**Comment by mondalaci** [comment]
The "Package" property is present in the generated panel.kicad_pcb file, but only for one J1 component, yet, this plugin shows it for all four J1 components.

**Comment by qu1ck** [comment]
I think I fixed it, try the latest master.

The whole logic of extra fields is quite messy because of legacy kicad support...

**Comment by mondalaci** [comment]
Your fix is working, and it's much appreciated.

I ended up writing a script that adds the Footprint properties based on footprint ids like this:

```python
for footprint in outline.GetFootprints():
    footprintId = footprint.GetFPIDAsString()
    if footprintId.startswith('S01_Hybrid_Socket_'):
        footprintId = 'S01_Hybrid_Socket'
    footprint.SetProperty('Package', footprintId)
```

Thanks for this tool! It's by far the most valuable KiCad plugin, and it makes assembly and communicating with our contract manufacturer so much better.
