### ISSUE TITLE
EasyEDA已经不支持导出json文件了，所以我应该怎么使用这个项目还是直接抛弃

### ISSUE THREAD

**Issue by mingtianshi** [openscopeproject/InteractiveHtmlBom#386]

**Comment by qu1ck** [comment]
Hope this translation is correct

![image](https://user-images.githubusercontent.com/3622532/236402686-eec80116-8b4c-43c2-94a3-46a65a9deb78.png)

I just checked and you can still export json so I am not sure what you mean.

![image](https://user-images.githubusercontent.com/3622532/236402806-a49ee6ce-3f7d-4817-9092-9b2b56c099e8.png)

**Comment by mingtianshi** [comment]
<img width="1279" alt="截屏2023-05-05 下午11 17 31" src="https://user-images.githubusercontent.com/74260755/236500185-c0a35db2-a7ba-46e9-8843-45b6c724abb3.png">
I am using the web version, and in fact, the same applies to using the ezyeda professional version.

**Comment by qu1ck** [comment]
That looks like EasyEDA Pro which is not supported because file format is not documented.

But it has built in soldering assistance tool with similar functionality

![image](https://user-images.githubusercontent.com/3622532/236589771-2ed585ca-488f-4aa1-9cc1-897e4d74da90.png)
