### ISSUE TITLE
AttributeError: 'BOARD' object has no attribute 'GetModules'

### ISSUE THREAD

**Issue by mondalaci** [openscopeproject/InteractiveHtmlBom#388]
I've recently upgraded to KiCad 7.0.2, and upon trying to generate the BOM, the following dialog appears.

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/300402/b423c42d-0683-429e-876e-8fb9b5c1ca5e)

**Comment by qu1ck** [comment]
You are running a very old version, update your plugin.
If you are running from kicad and not from terminal then just delete your old version and install from kicad's plugin manager.

**Comment by mondalaci** [comment]
I'm running the latest version, but I can't reproduce the issue anymore, so I'm unsure what was happening.

Thanks for the quick reply, and keep up the great work!

**Comment by qu1ck** [comment]
Judging from the paths in the error above you have ibom in your home dir, that is not standard location where plugin manager installs things.

If you run into this issue again then make sure to delete your manual installation folder and just install from plugin manager.
