### ISSUE TITLE
Feature Request: Placed parts are rendered differently

### ISSUE THREAD

**Issue by hacsccc** [openscopeproject/InteractiveHtmlBom#390]
While placing parts, it would be nice to have a visual feedback on the board-render which parts are already placed.
I propose to add a CSS class 'placed' that gets toggled once the placed checkbox is checked. Parts that are placed get rendered in a lighter tone.

Then, the user can see where on the PCB parts are not yet placed by looking at the canvas.

**Comment by cpresser** [comment]
That was my throwaway account. :facepalm:  I am commenting here to get proper notifications.

**Comment by qu1ck** [comment]
Also already done, in the settings menu you can switch which checkbox will be affect the render highlight.

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3622532/f121f3ad-9b15-4633-bf6c-5635f1df61eb)

Rows in the table don't need a highlight, checkbox itself is enough.
