### ISSUE TITLE
Feature Request: Progress bar

### ISSUE THREAD

**Issue by cpresser** [openscopeproject/InteractiveHtmlBom#391]
Gamification makes everything better. I use iBom in soldering workshops, there positive reinforcement ("you managed to place half of the parts") helps participants.

For large BOMs. that don't render fully on the screen without scrolling, this would be a nice indicator on how far one has already progressed in the assembly.

**Comment by qu1ck** [comment]
There is one already, tucked into the stats menu.

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3622532/3110c978-8247-4824-b0dc-3140bfde7634)
