### ISSUE TITLE
Creating and Saving Multiple HTML Files

### ISSUE THREAD

**Issue by ankithjv** [openscopeproject/InteractiveHtmlBom#396]
Everytime I create a new InteractiveHTMLBom it replaces the previous html file with the new one. How can I get it so the name of the html file created is different so I can save multiple boards as htmls?

**Comment by Funkenjaeger** [comment]
You can accomplish that with the command line argument `--name-format` [(wiki documentation)](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Usage)
