### ISSUE TITLE
Sheet path/name no longer available for export

### ISSUE THREAD

**Issue by Qix-** [openscopeproject/InteractiveHtmlBom#399]
HI there, firstly great plugin that has helped me save a bunch of time, so thank you so much for making it!

3-4 months ago I remember being able to export the sheet path/name as fields for grouping, but that no longer seems to be the case. When testing portions of the board, it was really helpful as the schematic had individual components broken out into sheets. Now it seems that functionality was removed, or I've done something to somehow disable it.

Is there a way to re-enable sheet names/paths, or was that removed from the plugin?

**Comment by qu1ck** [comment]
It wasn't removed but if you are using nightly the API changed and needs a compatibility fix.

Which kicad version are you using and which file are you using for extra fields? pcb or netlist or xml?

**Comment by Qix-** [comment]
This is 7.0.0 release build. I'm just clicking the button from the toolbar in the PCB editor and not changing any files.

**Comment by qu1ck** [comment]
Check which file shows up in the extra data file field

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3622532/2476260d-0ddb-4c7d-a13a-0a439941a67e)

By default ibom will pick supported file with latest modification date, supported files are .kicad_pcb, .net and .xml. But not all of them have support for sheet fields, if I remember correctly only .kicad_pcb provides those fields out of the box. So if you have a netlist file with later modification date it will be picked and sheetname fields will not show up. Make sure you update kicad_pcb and save it before running ibom.

**Comment by Qix-** [comment]
You nailed it, it was pulling an XML instead of the .kicad_pcb file. Saved the PCB and now the sheetfiles are showing up.

Thanks a lot!
