### ISSUE TITLE
Fields display corruption 

### ISSUE THREAD

**Issue by rgalland** [openscopeproject/InteractiveHtmlBom#400]
![messed_up_fields_window](https://github.com/openscopeproject/InteractiveHtmlBom/assets/27197663/6e0541eb-7cdd-440e-ab6c-5dbd746ad581)
This has happened since switching to Kicad 7.0. I have components that have a certain number of custom fields and it seems that iBom cannot cope with it. I ran some tests with a simple BOM and worked out that if I remove enough fields, the corruption disappears. Basically, the number of custom fields should not exceed 9. This is not something that used to happened when I used Kicad 6 and probably an older version of iBom.

**Comment by qu1ck** [comment]
I believe this was fixed in 3302982ea7918ce4544ec6c3b9f0ce0350b74f23

Can you try it? You will have to uninstall the plugin from kicad's plugin manager and follow manual installation instructions in wiki.

**Comment by rgalland** [comment]
Excellent, thank you for your quick response. I fixed the lines manually in the code for now and it works fine.
