### ISSUE TITLE
Version 2.7.0 still reporting 2.6.0

### ISSUE THREAD

**Issue by StormTrooper** [openscopeproject/InteractiveHtmlBom#404]
I've installed 2.7.0 with the latest KiCad 7.0.6

When running IHB it's showing 2.6.0 in the title. Is this due to version.py still showing 2.6.0?

```
LAST_TAG = 'v2.6.0'
```

Downloading InteractiveHtmlBom_v2.7.0_pcm.zip or InteractiveHtmlBom.zip shows 2.6.0 in the version.py file as well.

**Comment by qu1ck** [comment]
Yes, I forgot to bump version there. It's does not affect functionality.

**Comment by qu1ck** [comment]
2.8.0 should report correctly.
