### ISSUE TITLE
Coloring Nets

### ISSUE THREAD

**Issue by ankithjv** [openscopeproject/InteractiveHtmlBom#411]
When I color the nets can I highlight the complete net and all the pads as well and able to only color the pads connected to said net.

**Comment by ankithjv** [comment]
Can I add zoom functionality as well when I click on something on the table for components. and Hover functionality when I hover over a pin on the layout that gives me pin number and part number.

**Comment by qu1ck** [comment]
> When I color the nets can I highlight the complete net and all the pads as well and able to only color the pads connected to said net.

That is not supported currently. You should be able to tweak pad rendering color according to the net pretty easily with some custom js.

> Can I add zoom functionality as well when I click on something on the table for components. and Hover functionality when I hover over a pin on the layout that gives me pin number and part number.

These can also be done but 1) it should be in a separate wishlist issue 2) it's not well aligned with main use case of ibom and I will not prioritize it until templates are implemented.
If you want to implement it yourself, it's doable.
