### ISSUE TITLE
Support of KiCAD v7 Symbol attribute Do not populate

### ISSUE THREAD

**Issue by hwidvorakinfo** [openscopeproject/InteractiveHtmlBom#412]
The Schematic editor of KiCAD v7 allows setting the Do not populate attribute to each symbol. The iBOM can blacklist components with the DNP field, but the Do no populate attribute is not a field.

Please add this option to the iBOM plugin.

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/54349879/a6a13e33-cfda-46a3-b88f-2709c9569995)

**Comment by qu1ck** [comment]
Already implemented in f918435bee9ce7ecba96aee9f2ce3ecb14512333
It's not in release yet if you want it early you can grab master.
