### ISSUE TITLE
Component Sort Order ("Characters other than A-Z will be ignored")

### ISSUE THREAD

**Issue by tempohelmet** [openscopeproject/InteractiveHtmlBom#414]
I'd like to sort the components in a specific order to match an existing physical BOM kit, so I don't have to resort and relabel bags of components, but there doesn't seem to be a way to arbitrarily sort the parts in InteractiveHtmlBom.

I tried specifying the exact order (like "R1, R2, C1, U1, R3") by pasting the list into `config.ini` or `ibom.config.ini`, but the output html strangely came out relatively unsorted. 

It seems that even the statement "Characters other than A-Z will be _ignored_" isn't true, because I get a different (unsorted?) result if I specify numbers like "R1, C1, U1", compared to specifying just the prefix: "R, C, U".

**Comment by qu1ck** [comment]
> It seems that even the statement "Characters other than A-Z will be ignored" isn't true

It's true in GUI where that statement is. If you manually write something in the ini file it will likely behave differently and feel broken because it sorts based on prefix, not numerically.

To achieve what you want you should add a custom field like "kit order" and sort by that.
