### ISSUE TITLE
Feature Request: Highlight the placed components. 

### ISSUE THREAD

**Issue by abhinav937** [openscopeproject/InteractiveHtmlBom#421]
I think it would be nice if we can see the placed components on the board preview.

**Comment by qu1ck** [comment]
Already exists, set Marked when checked to desired checkbox 
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3622532/86844ff5-0883-4423-a359-91a540ab27e7)

**Comment by abhinav937** [comment]
Thanks, I didn't notice that properly.
