### ISSUE TITLE
one small request. Please implement the same script for Altium designer.

### ISSUE THREAD

**Issue by albtronics** [openscopeproject/InteractiveHtmlBom#423]
Hello developer,

Please implement the same plugin for **Altium Designer**.
When I moved to Altium for PCB designing, I really missed your InteractiveHTMLBom.

So, please do what's needed.

I really appreciate any help you can provide.

**Comment by qu1ck** [comment]
Altium file formats are not open and I don't have thousands of dollars to spend on their license and tens of hours to spend on reverse engineering them.

You can import your altium design into kicad and use the plugin from there.
