### ISSUE TITLE
How to use custom fields with Allegro

### ISSUE THREAD

**Issue by DaLaoHei1986** [openscopeproject/InteractiveHtmlBom#427]
![图片](https://github.com/openscopeproject/InteractiveHtmlBom/assets/58840112/4608b51e-dc7a-4891-a814-4ff651efdde9)

**Comment by qu1ck** [comment]
Assuming you are using kicad, edit the component fields in schematic, save it, update the pcb from schematic, save it, then use the "Fields" tab in plugin configuration to show/group the fields you want.

**Comment by DaLaoHei1986** [comment]
> 假设您使用 kicad，编辑原理图中的组件字段，保存它，从原理图更新 PCB，保存它，然后使用插件配置中的“字段”选项卡来显示/分组您想要的字段。

Unfortunately, I am using Allegro. Do you currently have any tutorials in this area?

**Comment by qu1ck** [comment]
According to JuulsA's comment in  https://github.com/juulsA/exportJson/issues/8 custom fields are supported by his export script.  In that case you just have to enable them in the bom config, either in gui if you use that, or with `--extra-fields` flag if you use only cli.

**Comment by DaLaoHei1986** [comment]
> 根据 JuulsA 在 [juulsA/exportJson#8 ](https://github.com/juulsA/exportJson/issues/8) 中的评论，他的导出脚本支持自定义字段。 在这种情况下，您只需要在 bom 配置中启用它们，如果您使用它，则可以在 gui 中启用它们，或者使用 `--extra-fields` 标记（如果仅使用 CLI）。
Thank you very much for your reply. I'll try it now
