### ISSUE TITLE
EAGLE 9.6.2: Bottom side component incorrect orientation.

### ISSUE THREAD

**Issue by depalamarchuk** [openscopeproject/InteractiveHtmlBom#429]
Hello,

The script either rotates a certain component by 180 degrees or mirrors it (not sure what happens here). The component is located at bottom side. I'm using the latest version. I ran the command:
`python "Z:\CAD\Electric CAD Libraries\EagleCAD\01_Sys\ibom\InteractiveHtmlBom\generate_interactive_bom.py" "C:\ibom mwe\mwe.brd" --name-format "%f BOM Rev ibom" --show-fabrication --include-tracks`

This is from EAGLE 9.6.2:
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/25909502/e43ee517-c896-4ad9-90a4-a4a943632869)

And this is the HTML BOM:
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/25909502/d5a2e688-3fca-4237-94b5-67ec166e9609)

I'm attaching a minimum project, so you can check it:
[ibom mwe.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/13248689/ibom.mwe.zip)

Thank you and have a nice day!

**Comment by Funkenjaeger** [comment]
Thanks for sharing an example demonstrating the problem, that's always appreciated!
I'm away from my computer for about a week so it'll be about that long before I'm able to debug this.  

Interestingly, from your screenshots it looks like only the half-circle was inappropriately mirrored.  The line segments (2 on the left, 1 on the right) look correct.

**Comment by qu1ck** [comment]
`L5` text is also rotated the other way.

**Comment by Funkenjaeger** [comment]
Fixed U7 arc mirroring and L5 text rotation in #433.

<img width="120" alt="image" src="https://github.com/openscopeproject/InteractiveHtmlBom/assets/24237058/8c102793-9be3-455f-a5f4-eb4ef504965d">
