### ISSUE TITLE
UX issue: Mousover highlighting parts of row.

### ISSUE THREAD

**Issue by mxa** [openscopeproject/InteractiveHtmlBom#437]
It happened to me more than once that during assembly something touched the mouse (or I had to wiggle the mouse to make the screensaver go away). The cursor now inadvertently moved to be over a different row without me being aware of that, continuing to assemble the current part into wrong places.
I think mouseover highlighting the parts of a row is not a good choice. The row should be _clicked_ instead to be selected (arrow keys could be used to select one after the other) and parts highlighted.

**Comment by qu1ck** [comment]
You can move the mouse away from the table and use only the arrow keys to switch rows.

You can also use custom script to use "click to select" logic https://github.com/openscopeproject/InteractiveHtmlBom/issues/88#issuecomment-650539158
