### ISSUE TITLE
Feature Request: Clear all Sourced / Placed flags at once

### ISSUE THREAD

**Issue by shufps** [openscopeproject/InteractiveHtmlBom#440]
Is it possible to add some option to clear all Source or Placed flags at once?

It happened a couple of times that I have to manually deselect everything that is selected from a previous assembly :see_no_evil:

**Comment by qu1ck** [comment]
If torrent is already added - click one row in files tab, press ctrl-a to select all, right click -> Set unwanted.
If you are adding it then press "None" button.

**Comment by qu1ck** [comment]
Um, I had a brainfart, thought this is another repo. To clear/set all just double click the checkbox column header.
