### ISSUE TITLE
Include tracks/zones not working.

### ISSUE THREAD

**Issue by dunk-law** [openscopeproject/InteractiveHtmlBom#441]
Using Kicad 7.0.10 & IBOM 2.8.0. Enabling inclusion of tracks and zones does not appear to work.

**Comment by qu1ck** [comment]
Don't forget to enable them in html page if you have previously generated bom without tracks/zones.

**Comment by dunk-law** [comment]
As far as I can tell the real bug lies in the sheet information.  I just filled in all the page settings and then the next IBOM output worked, including tracks.

**Comment by qu1ck** [comment]
What sheet information?
