### ISSUE TITLE
Filter on multiple schematic sheets

### ISSUE THREAD

**Issue by mcgdb** [openscopeproject/InteractiveHtmlBom#443]
Hi...Great plugin...We do a fair amount of in-house board assembly by hand, and I don't know how we'd live without this plugin!

I have a project where I jammed 3 boards, made up of 4 schematic sheets together into one KiCad project.

If I enable exporting the schematic sheets in the dialogue, they show up fine, and I can filter them based by typing in the schematic sheet name.

I have one board that is comprised of two schematic sheets...I usually print the BOM out directly from the browser and tape it on a piece of stencil-board to line up the component reels with double-stick tape, so I was wondering if I can filter for 2 schematic sheets instead of just one.

Thanks!

**Comment by qu1ck** [comment]
Advanced filtering syntax that would allow logical operators like "contains X or Y" or "contains X and Y" and so on are not supported.

* You can rename the sheets in kicad and add some project specific prefix that you will filter on
* You can add a project specific field to all components on your boards and use that field as whitelisted variant in ibom settings, that way you will generate completely separate BOMs per project that don't need additional filtering

Choose whichever fits your needs best.
