### ISSUE TITLE
Configurable keyboard bindings

### ISSUE THREAD

**Issue by sre** [openscopeproject/InteractiveHtmlBom#444]
Hi,

It's quite annoying for me, that the page binds `Alt-1` - `Alt-9`. On Linux browsers default to use that for switching between the tabs. Please make it configurable somehow.

Thanks,

-- Sebastian

**Comment by qu1ck** [comment]
You can do this with [customization](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Customization).

Add this to `user.js`
```js
var originalOnLoad = window.onload;
window.onload = () => {
    originalOnLoad();
    document.body.onkeydown = (e) => {
        if (e.altKey && e.key >= '1' && e.key <= '9') {
            // catch to stop propagation
            e.stopPropagation();
        }
    }
}
```
