### ISSUE TITLE
Polygons missing on Silkscreen rendering

### ISSUE THREAD

**Issue by sur5r** [openscopeproject/InteractiveHtmlBom#45]
Subject says it all.

IMHO does not impede usability, but might be confusing.

**Comment by qu1ck** [comment]
This is fixed in KiCad upstream. You need to get a nightly build or if you are on windows get patched bindings. 

> Custom shape pads and copper zone drawings in footprints are supported but you need patched version of KiCad python bindings. My patch was integrated in KiCad dev branch, if you install a recent nightly build custom pads and copper/silkscreen graphics will be rendered.

> You can also get prebuilt patched bindings for windows x64 KiCad 5.0 [here](https://github.com/openscopeproject/InteractiveHtmlBom/releases/download/v0.5/PatchedPythonBindings.zip).
