### ISSUE TITLE
kicad: dnp has no effect on Fab layers

### ISSUE THREAD

**Issue by nopeppermint** [openscopeproject/InteractiveHtmlBom#450]
in my current pcb Project I have moved the component outline + designator text to F/B.Fab Layer.

If I now would like to only show the mounted components, this is only possible if the pads are displayed, as "dnp outlined" has no effect on Fab layer items...

I would suggest completely removing the Fab attributes in case "dnp outlined" is checked.
Or any other solution, which makes dnp option checked visible on Fab layers.

Would be nice, if that could be added, thanks

Example print screens:

with pads visible, everything is ok:
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3403218/3e6760ec-7233-4200-bb27-c89e8b22b2b6)
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3403218/11e579ff-e5aa-47a9-aa9d-bb70d9743317)

pads not  visible (disabled), no difference with "dnp outlined" active:
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3403218/7502073f-e036-4dcb-9a99-2b17b857cfff)
![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/3403218/14012907-34ec-40d9-a588-55584a120351)

**Comment by nopeppermint** [comment]
I am on commit https://github.com/openscopeproject/InteractiveHtmlBom/commit/a0887b33803ee912109b96742a8c2a1587c71d48

with Kicad:

```
Application: KiCad PCB Editor x64 on x64

Version: 8.0.2-124-g1264230973, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.12.1
	HarfBuzz 8.3.0
	FontConfig 2.14.2
	libcurl/8.5.0-DEV Schannel zlib/1.3

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW
OpenGL: ATI Technologies Inc., AMD Radeon(TM) 780M, 4.6.0 Compatibility Profile Context 22.40.70.16.231017

Build Info:
	Date: May 19 2024 05:22:18
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.8.1
	Curl: 8.5.0-DEV
	ngspice: 42
	Compiler: Visual C++ 1939 without C++ ABI

Build settings:

```

**Comment by nopeppermint** [comment]
minimal example project to reproduce it:
[interactive_html_bom_example.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/15387080/interactive_html_bom_example.zip)

**Comment by qu1ck** [comment]
This was discussed earlier, see https://github.com/openscopeproject/InteractiveHtmlBom/issues/336#issuecomment-1323722800

I'll close this as a duplicate, follow that issue for updates.
