### ISSUE TITLE
Board Heatmap Feature

### ISSUE THREAD

**Issue by ankithavn** [openscopeproject/InteractiveHtmlBom#451]
Hi, 

Thanks for an awesome plugin! 

Additionally, I am trying to use this plugin as a base to create a heatmap of a motherboard to show which parts have the most defects during production. How would you recommend going about it? I am currently planning on adding the defect gradient to each reference in the JSON and then adding JavaScript functions to also parse that data into colors on the HTML. Or should I edit the already created HTML? Can you point me to the right sections in the code to do so? 

Thanks!

**Comment by qu1ck** [comment]
To change how rendering looks you can use [custom javascript](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Customization) and override drawing code where needed. This is how the footprint and highlight box around it is drawn
https://github.com/openscopeproject/InteractiveHtmlBom/blob/a0887b33803ee912109b96742a8c2a1587c71d48/InteractiveHtmlBom/web/render.js#L319

You can trace where that function is called and add your own calls to draw differently colored boxes on top or whatever you want.

In terms of how to inject the gradient data you can either have that as a custom field in kicad and then use that custom field in bom and your rendering code or modify the python code to add the gradient to footprint structure itself. Check DATAFORMAT.md file and look around this area for code responsible for fp data
https://github.com/openscopeproject/InteractiveHtmlBom/blob/a0887b33803ee912109b96742a8c2a1587c71d48/InteractiveHtmlBom/ecad/kicad.py#L571

**Comment by ankithavn** [comment]
Thanks!
