### ISSUE TITLE
"Highlight first pin" option is cluttered in macOS

### ISSUE THREAD

**Issue by showier-drastic** [openscopeproject/InteractiveHtmlBom#452]
<img width="137" alt="image" src="https://github.com/openscopeproject/InteractiveHtmlBom/assets/168159404/a56d2964-37f7-4259-91cb-7078ecde3bd6">

The three radio buttons are overlapped.

Plugin version: 2.9.0
Kicad version: 8.0.2
on macOS 14.3.1 (ARM)

**Comment by showier-drastic** [comment]
This seems to be a bug of wxWidgets (or wxpy) bundled by KiCad.

```python3
import wx

class Frame(wx.Frame):
    def __init__(self, title):
        wx.Frame.__init__(self, None, title=title, pos=(150,150), size=(350,200))
        panel = wx.Panel(self)
        box = wx.BoxSizer(wx.VERTICAL)

        highlightPin1Choices = [ u"None", u"All", u"Selected" ]
        self.highlightPin1 = wx.RadioBox(panel, wx.ID_ANY, u"Highlight first pin", wx.DefaultPosition, wx.DefaultSize, highlightPin1Choices, 3, wx.RA_SPECIFY_COLS )
        self.highlightPin1.SetSelection( 0 )
        box.Add( self.highlightPin1, 0, wx.ALL|wx.EXPAND, 5 )

        panel.SetSizer(box)
        panel.Layout()

app = wx.App()
top = Frame("a")
top.Show()
app.MainLoop()
```

Upstream wxWidgets and wxpy:

<img width="462" alt="image" src="https://github.com/openscopeproject/InteractiveHtmlBom/assets/168159404/7dd3a86e-a3a3-46f4-8cc5-b93c7e56bae2">

KiCad bundled wxpy:

<img width="462" alt="image" src="https://github.com/openscopeproject/InteractiveHtmlBom/assets/168159404/73cd6e9e-66b0-4666-9758-6b7fc18580a5">

**Comment by qu1ck** [comment]
Thanks for checking if it reproduces on upstream, it does seem like something is wrong in kicad's fork of wx.
