### ISSUE TITLE
Highlight first pin in settings has no effect

### ISSUE THREAD

**Issue by viktak** [openscopeproject/InteractiveHtmlBom#454]
First: Thanks for this great plugin - I use it all the time.

However, I just noticed, that (as the title says) that the `Highlight first pin` in settings (see screenshot below) has no effect in the resulting HTML file, i.e. the first pins are always highlighted. Once in the HTML file in a browser, I can set the same thing, and it actually works.

![image](https://github.com/openscopeproject/InteractiveHtmlBom/assets/12509879/c435f4b8-babd-45a6-8469-9731591c08ee)

Given that I recently updated to KiCAD 8.0.3, and before I didn't notice this behavior, it is possible, that it started now. Now I can't go back to KiCAD 7 to test this, though.

I also tried to save the settings (both locally and globally), but it wouldn't make a difference.

**Comment by qu1ck** [comment]
This works as intended. The configuration in dialog is for html **defaults**. I.e. what the browser will show if you load the page for the first time. If you have changed some settings in the browser they will be remembered.

**Comment by viktak** [comment]
Aaaah, I see. My bad. Sorry about that!
