### ISSUE TITLE
big, comfortable checkboxes in table

### ISSUE THREAD

**Issue by mkdugi** [openscopeproject/InteractiveHtmlBom#455]
Hi,

First of all, thank You for your plugin! :-)

I'm trying to use in on cheap laptop with touchscreen and Linux, to help myself with soldering my plates.
But box to checkbox in "Sourced" and "Placed" columns are small and hard do hit with finger.
My proposal is to make this checkboxes as big as cells where they are placed. This cells exists only for this checkboxes, so area around checkboxes is not important.
This would make use of this plugin much easier on touching devices :-).

![Screenshot from 2024-07-12 09-59-21](https://github.com/user-attachments/assets/6b29fa25-190a-4600-b14c-eb046eb901db)

**Comment by qu1ck** [comment]
I think keeping the default appearance but making the whole cell area act as checkbox on touch devices is better.

**Comment by mkdugi** [comment]
> I think keeping the default appearance but making the whole cell area act as checkbox on touch devices is better.

Yes! It's absolutely very good solution! 
Unfortunately, i'm not a JS/HTML programmer :-(, I can't help. But I can test! :-).
