### ISSUE TITLE
Not working in kicad-nightly-8.99

### ISSUE THREAD

**Issue by wiserst** [openscopeproject/InteractiveHtmlBom#459]
I would really need the plugin to work in kicad-nightly-8.99. Please would that be possible? If a financial contribution is necessary, write to me. Thank you very much.

**Comment by qu1ck** [comment]
Should be fixed after https://gitlab.com/kicad/code/kicad/-/merge_requests/1981 is merged and new nightly is available.

No need for contribution, you can donate to kicad instead.

**Comment by qu1ck** [comment]
Fixed now, update your nightly.
