### ISSUE TITLE
wxPython release number mismatch

### ISSUE THREAD

**Issue by aaronw2** [openscopeproject/InteractiveHtmlBom#46]
Which version of WxWidgets is required? OpenSUSE supports WxWidgets 3.0 for Python.
I get the below output when I attempt to run it. I am running on OpenSUSE Leap 15.0:

Run command:
python "/home/aaronw/kicad/scripts/InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py" "/home/aaronw/kicad/Ralph/led-controller-wrover32/led-controller-wrover32/led-controller-wrover32.xml" "/home/aaronw/kicad/Ralph/led-controller-wrover32/led-controller-wrover32/led-controller-wrover32"

Command error. Return code 2
Error messages:
/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
usage: generate_interactive_bom.py [-h] [--nobrowser] file
generate_interactive_bom.py: error: unrecognized arguments: /home/aaronw/kicad/Ralph/led-controller-wrover32/led-controller-wrover32/led-controller-wrover32

**Comment by qu1ck** [comment]
wxWidgets related output is just a warning, ignore it.

Please look at the example from readme:
```
python2 path/to/InteractiveHtmlBom/generate_interactive_bom.py path/to/board.kicad_pcb
```

You don't need to pass any xml files as arguments, only the board file.
