### ISSUE TITLE
Missing some Pin 1 silkscreen triangles

### ISSUE THREAD

**Issue by totallymindblown** [openscopeproject/InteractiveHtmlBom#465]
_Tested versions:_

**KiCad 8.0.4
InteractiveHtmlBom 2.9.0**

Some of the pin 1 triangles from silkscreen layer are not rendered.
This means that a clear orientation using **ibom.html** is not possible.

Example packages where pin 1 triangle does not show up in **ibom.html**:

- Package_TO_SOT_SMD:SOT-23-6
- Package_QFP:TQFP-100_14x14mm_P0.5mm

![kicad](https://github.com/user-attachments/assets/5e6d703d-b504-4382-916b-66795741821a)

![ibom](https://github.com/user-attachments/assets/4127aa9b-ffa9-4f39-9282-aac4d33b6d82)

**Comment by qu1ck** [comment]
Can you check with ibom from git latest? I think this was fixed in 002d62760ae2c91a267d8c8d2a3b5eccf81439a2

**Comment by totallymindblown** [comment]
I downloaded hole repo and installed the plugin manually and it is working now.
Problem solved. 🍓 
Thank you. 😃

**Comment by qu1ck** [comment]
Great.
I really should cut a release soonish...
