### ISSUE TITLE
Silkscreen not showing completely

### ISSUE THREAD

**Issue by doadoaf24** [openscopeproject/InteractiveHtmlBom#468]
Thank you for this tool, I started using it and noticed that a few marks pointing to pin 1 in the silkscreen are not showing
here is the 3d view
![image](https://github.com/user-attachments/assets/8200954d-a826-4d44-b0fd-e25033df9ad9)
this is the pcb
![image](https://github.com/user-attachments/assets/af492a5e-3222-42a5-b6b8-73de9419c7aa)
this is the tool you can see the small triangle pointing to pin 1 is not there
![image](https://github.com/user-attachments/assets/f89ad410-6ed4-4bb5-9a36-a4615d0c13e3)

this is happening with a few other footprints in the board.

**Comment by doadoaf24** [comment]
This is the footprint triangle
![image](https://github.com/user-attachments/assets/dd41dde0-d849-4811-ab17-675e4cb03259)

**Comment by qu1ck** [comment]
Duplicate https://github.com/openscopeproject/InteractiveHtmlBom/issues/465

This is fixed already but not released yet.
