### ISSUE TITLE
I wish the row selection did not move on hover

### ISSUE THREAD

**Issue by vishnumaiea** [openscopeproject/InteractiveHtmlBom#474]
Thanks for the great plugin. It is exceptionally simple and useful for design verification and assembly.

The only thing I found annoying is how the row seleciton moves by **hovering**. When you click on a part on the PCB, it gets highlighted in the table. If you accidentally move the mouse over the table, the selection is gone 🥲. Can be very annoying when you have to switch between a mouse, tweezer and a soldering iron.

**Comment by vishnumaiea** [comment]
Found a solution here https://github.com/openscopeproject/InteractiveHtmlBom/issues/88

**Comment by qu1ck** [comment]
Reminder that you can use the keyboard arrow keys to change row selection.
