### ISSUE TITLE
Layer transition holes

### ISSUE THREAD

**Issue by bms-2015** [openscopeproject/InteractiveHtmlBom#477]
Hello. 
Maybe I don't fully understand, but I don't see the holes of transition to another layer on the diagram taken from EasyEDA.
Appears as a track break.

![Clipboard_11-02-2024_02](https://github.com/user-attachments/assets/ca1fcded-75df-45d3-89b0-055bb31b3ee5)

![Clipboard_11-02-2024_021](https://github.com/user-attachments/assets/504f7baa-fcdc-4c81-aa41-5c161855c240)

**Comment by qu1ck** [comment]
I just added via support. Note actual holes of the via are not drawn, that is intentional because they are usually covered by soldermask. But you will see the via outline similar to trracks.
