### ISSUE TITLE
Feature request: fade placed components

### ISSUE THREAD

**Issue by jenschr** [openscopeproject/InteractiveHtmlBom#479]
I love the highlighting of placed components, but they're really standing out? I would love for placed components to be set to 50% alpha or something that makes it easier for color blind to see if something is placed or not.

Thanks a lot for making this plugin! Makes my prototyping so much easier!

**Comment by qu1ck** [comment]
You can tweak the colors as you wish with custom css, see customization page on the wiki.
But I suggest you invert the flag instead, so that it will be marked when component is **not** placed. That way the bright will mean "yet to be placed" and easy to see.

**Comment by jenschr** [comment]
Brilliant!
