### ISSUE TITLE
(Minor issue) Export/copy of BOM list: Add position column name

### ISSUE THREAD

**Issue by mMuck** [openscopeproject/InteractiveHtmlBom#480]
Thanks for that great plugin!

I saw that the list position column exports as `null`. Could this be set to `Position` or `Pos`?
```
null	References	Value	Footprint	...
1	R167, R168, R193, R194, R195, R196,...
2	R115, R126, R128, R153, R156, R162,...
```

**Comment by qu1ck** [comment]
Thanks, It's supposed to be empty. Fixed now, you can install latest from master manually or wait for next release in kicad's plugin manager.
