### ISSUE TITLE
Allow selecting single component and iterating through components of a group

### ISSUE THREAD

**Issue by MrSurly** [openscopeproject/InteractiveHtmlBom#52]
Essentially highlight a single component from a group (e.g. only highligh R1 from the R1, R7, R23 group of 10K resistors), and have a "prev" and "next" button to step through the various locations of the parts in the group.

**Comment by qu1ck** [comment]
I wanted to do this with left/right arrow keys but this needs a good bit of refactoring. Probably won't happen until v2.

**Comment by qu1ck** [comment]
References will be clickable too.

**Comment by qu1ck** [comment]
BOM can ungroup the table and show each component on individual row. This is more generic solution to the problem discussed above. This can be closed now.
