### ISSUE TITLE
Drone CI/CD plugin - just an info

### ISSUE THREAD

**Issue by zen** [openscopeproject/InteractiveHtmlBom#61]
Hi,

Just an info, I adapted your script to be run from drone CI/CD as a plugin. 
https://hub.docker.com/r/surgecloud/drone-kicad-ibom/

It uses minimized docker image based on Debian to run headless kicad. 

Drone CI/CD is very interesting CI system based on docker. There is another great work made by Toroid company:
https://github.com/Toroid-io

**Comment by qu1ck** [comment]
Thanks.
I don't really have any experience with docker. If you put together some documentation or quick start guide on how to hook up drone and your plugin I'll be happy to put it on wiki. A good short pitch to showcase how it's useful for someone not familiar with CI would also be good. As software engineer I'm well familiar with the latter in my field but I am not convinced about value it brings to EE field. There just isn't that much direct collaboration and not nearly as many revisions that need "integration" as in software. But maybe I'm just looking at it through a hobbyist's glasses.
