### ISSUE TITLE
Cannot run from KiCad v5

### ISSUE THREAD

**Issue by gcormier** [openscopeproject/InteractiveHtmlBom#64]
I just did a recent pull and it seems to have broken something. Unfortunately I don't know what version I was running prior.

It has to do with the command line arguments.

``` 
python "D:\kicad\plugins\InteractiveHtmlBom\InteractiveHtmlBom/generate_interactive_bom.py" "%I" "%O"
```
This fails, with

```
Traceback (most recent call last):
  File "D:\kicad\plugins\InteractiveHtmlBom\InteractiveHtmlBom/generate_interactive_bom.py", line 695, in <module>
    board = pcbnew.LoadBoard(os.path.abspath(args.file).decode('utf8'))
  File "C:\Program Files\KiCad\lib\python2.7\site-packages/pcbnew.py", line 8401, in LoadBoard
    return _pcbnew.LoadBoard(*args)
IOError: Unknown file type
```

However, if I just hardcode the command in KiCad to be 

```
python "D:\kicad\plugins\InteractiveHtmlBom\InteractiveHtmlBom/generate_interactive_bom.py" "C:\Users\Greg\Desktop\megadesk\PCB\megadesk.kicad_pcb"
```
It runs perfectly.

I'm unsure how to set the parameter in KiCad to something other then the XML file, and I couldn't find any information on this. If it's possible to do so, it would be useful in the documentation for InteractiveHtmlBom. If not, then it might be necessary to parse the XML file?

**Comment by qu1ck** [comment]
You are trying to use it from eeschema which is not supported. You need to use it from pcbnew instead. Read wiki for installation and usage instructions:
https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Installation

**Comment by gcormier** [comment]
Brain fart on that one! :)

Perhaps a simple output message if an XML file is passed? "Please run from pcbnew."
