### ISSUE TITLE
Plugin's output doesn't contain at least one part

### ISSUE THREAD

**Issue by a-k-goncharov** [openscopeproject/InteractiveHtmlBom#69]
What's up guys,
First of all, I want to thank you for this really awesome and very practical plugin. Since now our soldering-guys will say less "dirty" words while introducing to new PCB. 
But.. I've found a bug(?) in a trunk version of the plugin. For some reasons the part list isn't full - it doesn't contain at least one part. But.. at the same time the part appears on the PCB's layer. Don't know what is it..  I ran the script from console in Ubuntu 18.04 x64 environment.
I'm very interested to share the final *.kicad_pcb/netlist/whatever you ask - to fix this bug. But unfortunately i can't upload it to the public. I wasn't able to find your, @qu1ck , email here .. at github.. So.. is it interesting for you and do you have enough time to figure it out? How can we contact in a private?

**Comment by qu1ck** [comment]
Github doesn't show emails (for good reasons) but if you checkout the repo and peek into git log you will see my email. Also you can contact me on kicad.info forum as explained in FAQ.

But before you do any of that: most likely part is not in the bom because it is either marked as virtual or has duplicate reference number. For first you can just untick corresponding option in dialog, for latter change the reference.
If it's none of those, feel free to share your kicad_pcb with me and I'll take a look.

**Comment by qu1ck** [comment]
Since you run from console use `--no-blacklist-virtual` flag instead of dialog option.

**Comment by a-k-goncharov** [comment]
> Github doesn't show emails (for good reasons) but if you checkout the repo and peek into git log you will see my email. Also you can contact me on kicad.info forum as explained in FAQ.
I'm sorry - didn't pay attention to that option. But since now will keep it in mind.

> But before you do any of that: most likely part is not in the bom because it is either marked as virtual or has duplicate reference number. For first you can just untick corresponding option in dialog, for latter change the reference.
Thank you very much, sir! It was exactly it - marked as virtual. I even haven't known about this feature.. so can't answer how much did I drink before setting this option up...

Thank you, sir! I'll be following the project

**Comment by qu1ck** [comment]
> I even haven't known about this feature.. so can't answer how much did I drink before setting this option up.
You can rest assured that you weren't losing your mind, that option is on by default :)
