### ISSUE TITLE
Add controls to only show front/back components in bom

### ISSUE THREAD

**Issue by qu1ck** [openscopeproject/InteractiveHtmlBom#7]

**Comment by Sembazuru** [comment]
With this, I would suggest changing the viewing control for the board representation. Have a 3-way button (like the current board view) to show F, FB, and B in the BOM, and a 2-way button for the board view for "active BOM view" and "both sides". 

Or, I suppose, for simplicity sake, use the same button set for both. When the board view is front, only show the front components in the BOM. When board view is back only show back components. And, when both sides on board view show all the components.

**Comment by qu1ck** [comment]
Yeah, I was planning to use existing F/FB/B buttons to filter bom as well. Seems simple and effective.
