### ISSUE TITLE
PCBnew crashes Kicad after plugin installation

### ISSUE THREAD

**Issue by sandhan26** [openscopeproject/InteractiveHtmlBom#70]
Hi, I installed the plugin into the ~/.kicad_plugins folder. But after installation whenever I try to Open PCBnew, entire KiCAD crashes.

Without the plugin, in the ~/.kicad_plugin folder the PCBnew works normally.

I am working on Ubuntu 18.04, and my KiCAD version info is as follows : - 

Application: kicad
Version: 6.0.0-rc1-unknown-55b5c71~66~ubuntu18.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Platform: Linux 4.15.0-44-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 2.24
    Boost: 1.65.1
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.58.0
    Compiler: GCC 7.3.0 with C++ ABI 1011
Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=OFF
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=OFF
    KICAD_SCRIPTING_WXPYTHON=OFF
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

**Comment by qu1ck** [comment]
> Ubuntu 18.04
> wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 2.24

There's your problem. Read the [FAQ](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/FAQ#q-kicad-crashes-when-i-install-this-plugin-im-using-linux) and this issue #47.

You either have to compile KiCad yourself with GTK3 support or use plugin from command line.

**Comment by sandhan26** [comment]
Thanks man!
