### ISSUE TITLE
Where is "Donate" button?

### ISSUE THREAD

**Issue by rusefi** [openscopeproject/InteractiveHtmlBom#71]
I am unable to find any "Donate" buttons, please fix this ASAP! I need to thank the creators of this amazing tool.

**Comment by qu1ck** [comment]
Please see last question in [FAQ](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/FAQ#q-this-is-awesome-can-i-donate-to-this-project).

**Comment by rusefi** [comment]
Thank you @qu1ck, will do!

**Comment by qu1ck** [comment]
Done, thanks.
