### ISSUE TITLE
Error running in python3

### ISSUE THREAD

**Issue by diggit** [openscopeproject/InteractiveHtmlBom#73]
Running **InteractiveHtmlBom** from cli using python3, I got error:
```
AttributeError: 'str' object has no attribute 'decode'
```

Solution was easy, just remove `.decode('utf-8')` from 2 lines. I know that such change breaks python2 compatibility. Not sure about proper solution.

**Comment by qu1ck** [comment]
Thanks, I have a fix ready, will test tomorrow on gtk3/wxphoenix machine.

**Comment by qu1ck** [comment]
Fixed in e594337

**Comment by Shackmeister** [comment]
@qu1ck Download newest version, now I get this

![interactive_exception](https://user-images.githubusercontent.com/5279723/53125270-e616df00-355d-11e9-87c6-2ccee61df125.png)

**Comment by qu1ck** [comment]
That was not related to python3 but that is now fixed too.

**Comment by Shackmeister** [comment]
my bad :) thank you!

**Comment by qu1ck** [comment]
No worries, thanks for reporting bugs.

**Comment by diggit** [comment]
Awesome, thanks for fixing.
