### ISSUE TITLE
Display DNP components half transparent

### ISSUE THREAD

**Issue by stiff** [openscopeproject/InteractiveHtmlBom#75]
Components marked as DNP are still visible in the pcb view, and at first it's quite confusing why is nothing happening when I click the component. I think it should be visible, but with reduced opacity, like 30% or so.

**Comment by qu1ck** [comment]
I found out that transparency doesn't work well in practice, at least not with current color scheme. I did outline mode instead, you can try it here: https://openscopeproject.org/InteractiveHtmlBomDemo/html/hp34401a_oled.html
