### ISSUE TITLE
Black and white list doesn't appear with large extra fields

### ISSUE THREAD

**Issue by hildogjr** [openscopeproject/InteractiveHtmlBom#81]
When is listed a "large" list of extra fields the black and white checkbox list list doesn't appear.
I am using Ubuntu 16.04.

Normal condition:
![Screenshot from 2019-03-12 13-17-25](https://user-images.githubusercontent.com/2211474/54216977-7e531480-44c9-11e9-8c03-eff0449743c5.png)

Issue:
![Screenshot from 2019-03-12 13-16-45](https://user-images.githubusercontent.com/2211474/54216989-857a2280-44c9-11e9-8d86-4bb0732a0c9a.png)

Work around: the extra filed checkbox list should have the scrollbar enabled.

**Comment by qu1ck** [comment]
This was a tricky one. wxCheckListBox sets it's size on frame init based on it's contents and doesn't care about any setSize, setMaxSize() calls later. Overrides any proportion directives of parent sizers etc.
