### ISSUE TITLE
Add option to show datasheet field as extra field

### ISSUE THREAD

**Issue by qu1ck** [openscopeproject/InteractiveHtmlBom#82]
Datasheet field is a built in and needs special handling because it's stored differently.

**Comment by hildogjr** [comment]
May use as hyperlink in a existent column at generated iBOM.

**Comment by eeintech** [comment]
@qu1ck Would you consider adding the "Datasheet" field in the list of fields since the format update in KiCad V6 doesn't differentiate it from other properties?

```
(property "Value" "CAP-000008-00" (id 1) (at 0 -15.24 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (property "Footprint" "Capacitors:C0402" (id 2) (at 0 -22.86 0)
        (effects (font (size 1.27 1.27)) hide)
      )
      (property "Datasheet" "http://xxx.com/" (id 3) (at 0 -13.97 0)
        (effects (font (size 1.27 1.27)) hide)
      )
```

**Comment by qu1ck** [comment]
It is stored similarly to other properties in the schematic but ibom doesn't read schematic file. It reads either netlist or pcb file. Datasheet field is not exported to the pcb so you have to generate netlist file if you want to use datasheet field.

**Comment by eeintech** [comment]
@qu1ck Yes it does work exporting the netlist. Follow-up question: can certain field be treated as hyperlink inside the HTML table?

In summary I would like this:
![image](https://user-images.githubusercontent.com/4020546/186422965-6fc33775-aa5f-4eca-b8ab-092dd5fb9db1.png)

To become:
![image](https://user-images.githubusercontent.com/4020546/186423944-ae6acf6f-89f3-448b-822f-c8399fb6c1df.png)

I could do a simple regex on the HTML, but I wonder if this feature is built-in somewhere?

**Comment by eeintech** [comment]
Actually never mind on the Regex... I didn't realize the data was compressed.

**Comment by qu1ck** [comment]
You can do any kind of postprocessing you want using [customization](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Customization).

**Comment by eeintech** [comment]
Thanks, I'll take a look!

**Comment by eeintech** [comment]
Alright figured it out, even with my poor JS skills :sweat_smile: 

For anyone looking to add datasheet links to the BOM table, using KiCad V6:
1. Go to schematic, click on "File > Export > Netlist..." and export netlist
2. Go to layout, in the menu bar click on "Preferences > Preferences > Action Plugins" and find out what is the folder used for the InteractiveHtmlBom plugin. Open that folder.
3. Copy `user.js` file inside folder "web/user-file-examples" to the "web" folder, along with other `*.js` files
4. Edit this file and add the following javascript code:
``` js

function urlify(text) {
    var urlRegex = /(https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*))/g;
    return text.replace(urlRegex, function(url) {
        return '<a href="' + url + '" target="_blank">' + url + '</a>';
    })
}

window.addEventListener('load', function() {
    var table = document.getElementById("bomtable");
    
    for (var i = 0; i < table.rows.length; i++) {
        table.rows[i].innerHTML = urlify(table.rows[i].innerHTML)
    }
});
```
6. Go back to KiCad layout, open InteractiveHTMLBOM plugin, select "Fields" tab, click "Show" checkmark next to `Datasheet` field (`Datasheet` field should be present in the list, else you've missed step 1).
7. Click "Generate BOM"
8. Enjoy hyperlinks!

@qu1ck Would you mind adding a link to this comment to this section of the doc, if you find it useful?https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Customization#examples

**Comment by qu1ck** [comment]
Your code will work only once when page is loaded. Any time bom table is changed (with filtering or display mode or checkbox change) your links will disappear because the table is regenerated.

You should add a listener to BOM_BODY_CHANGE_EVENT event, the see user.js example.

**Comment by eeintech** [comment]
Thanks, I have update my code snapshot above to make it a callback instead :+1:

**Comment by qu1ck** [comment]
Added to wiki.

**Comment by itsboo07** [comment]
> For anyone looking to add datasheet links to the BOM table, using KiCad V6:

How do I get this working with easyeda? also more than data sheet i want to create clickable url for references or values which takes to that specific product buy link.? any wrong around or suggestions?

**Comment by qu1ck** [comment]
Urls are detected automatically now since 39fc0c466cf1bd98464efae56c9713aaddbeb5a3 as long as it's the only thing in your field. 

But extra fields are not supported in easyeda. I see that they now added support to put custom fields in each component but there is no convenient way to bulk edit all components because BOM table doesn't show custom fields.

If anyone wants to add support to parse custom fields in easyeda parser I'll review it but I don't have time to add it right now.

**Comment by itsboo07** [comment]
> If anyone wants to add support to parse custom fields in easyeda parser I'll review it but I don't have time to add it right now.

thanks alot. please update me when you get it working.

**Comment by qu1ck** [comment]
I filed #348 to keep track of it.
