### ISSUE TITLE
Can't click on a component through a virtual component

### ISSUE THREAD

**Issue by dhaillant** [openscopeproject/InteractiveHtmlBom#87]
Hi,
I have a board which goes behind a front panel. I use a virtual component in Pcbnew to help me place the controls (potentiometers, etc).
This virtual component is bigger than the board itself and it "recovers" the other components.

Now, if that front panel component is set as "Through hole", when I click on the ibom map, I'm able to select a component (it's either the front panel that is selected or the component "behind" it).

But, if I set the front panel as a "Virtual" component, I can't select the components "behind" it. The check box "blacklist virtual components" is set but still, it avoids selecting components "behind" it.

I have to delete the virtual component in order to be able to click on the components in the map view.

Thank you
David

**Comment by qu1ck** [comment]
Thanks for bug report, let me know if fix works for you.

**Comment by dhaillant** [comment]
It works! Thank you very much!
