### ISSUE TITLE
Chinese footprint name is not supported 

### ISSUE THREAD

**Issue by zhqsoft** [openscopeproject/InteractiveHtmlBom#89]
Chinese footprint name is not supported

**Comment by qu1ck** [comment]
I can not reproduce this issue. Add more details and repro steps, if possible share the board file that shows the issue.

**Comment by zhqsoft** [comment]
If the footprint name value has Chinese characters, IBOM file cannot be exported .
I use the latest unpublished tools. 
Version V2.0 release is OK 

![QQ截图20190408142413](https://user-images.githubusercontent.com/48981799/55702764-29dc7f80-5a0a-11e9-994c-d893cfa53097.jpg)
![QQ截图20190408142435](https://user-images.githubusercontent.com/48981799/55702770-2d700680-5a0a-11e9-9166-795203d9eec8.jpg)

[CN_name_TEST.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/3052882/CN_name_TEST.zip)

**Comment by qu1ck** [comment]
I see, yeah that is because of recently added fab layer support. Will fix soon.
