### ISSUE TITLE
When zooming in the preview,The Front preview shows slowly.

### ISSUE THREAD

**Issue by zhqsoft** [openscopeproject/InteractiveHtmlBom#97]
Is there a problem with version V2.1? When zooming in the preview ,The Front preview shows slowly.The bottom preview is good. 
I uploaded BOM files and PCB files 
[7381.zip](https://github.com/openscopeproject/InteractiveHtmlBom/files/3147283/7381.zip)

**Comment by qu1ck** [comment]
I opened your file and don't notice any issues. Do you mean the rendering is slow? There are more elements on top preview than on the bottom but it's not particularly complex board. Can you open motherboard demo ok? 
Do you notice slowness only when zooming or when draggin as well?

What browser do you use?

**Comment by zhqsoft** [comment]
I use EDGE browser, bad browser .Google Chrome browser can be used properly .

**Comment by zhqsoft** [comment]
Another problem ,
The more electronic components, the thicker the silk screen rendering. 
![QQ截图20190507080822](https://user-images.githubusercontent.com/48981799/57262625-79f94100-709f-11e9-9e9e-b79010d99967.jpg)

**Comment by qu1ck** [comment]
Thanks. Interestingly the issue was there for a long time, it just became slightly more noticeable with recent changes.
