### ISSUE TITLE
Proposal: Shared Plugin Development Repository

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [openscopeproject/InteractiveHtmlBom#98]
Hello! 
This is a request for a YES/NO vote for the following proposal:
**Shared development of tools, scripts, plugins for KiCad EDA**
https://github.com/kicad-extra/arkon/issues/1
Thank you, and apologies if you already responded or otherwise not interested.

**Comment by qu1ck** [comment]
Voted.

**Comment by Andrei-Pozolotin** [comment]
thank you
